### ISSUE TITLE
crash on IOS 11.4

### ISSUE THREAD

**Issue by shuuha** [react-native-webview/react-native-webview#1003]
With the hidekeyboardaccessoryview set to true on IOS 11.4 the app is crashing.

this is the code block the xcode is showing when the app crashes

on file RNCWebView.m line 32
for some reason the if condition causing the crash.

![image](https://user-images.githubusercontent.com/32106081/68401501-aa7b7e00-019b-11ea-949c-ae902dd6aed2.png)

Unfortunately I am unfamiliar with Objective-c to propose my own solution for this bug.
Would be very grateful for some insight on this or better the fix of this bug.

**Comment by jvandijk** [comment]
I can confirm this issue. Also experiencing it in our app. It's not limited to iOS 11.4 but occurring for all iOS 11 versions.

The problem was introduced while fixing iPad compatibility: https://github.com/react-native-community/react-native-webview/pull/661

The only option you right now have is to use the following setting for iOS 11: `hideKeyboardAccessoryView={false}` showing the input field indicators.

**Comment by bryvin** [comment]
This issue still appears to exist in the current version, months later. Any update on when a potential fix may be out for this? Brining back the accessory view isn't very ideal.

**Comment by philpettican** [comment]
I've just run into this as well on devices < iOS 12. Can this be reopened?
