### ISSUE TITLE
Module is not a registered callable module(calling onMessage)

### ISSUE THREAD

**Issue by mezalejandro** [react-native-webview/react-native-webview#1324]
**Bug description:**

On Android I have the bug invariant violation: Module is not a registered callable module (calling onMessage)

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/568141/79476804-d539f000-7fdf-11ea-9544-52243682fe93.png)

**Environment:**
 - OS:  Android
 - OS version:
 - react-native version: 0.61.5
 - react-native-webview version: ^9.2.1

**Comment by MatteoPironi** [comment]
Same here with Android, the last version that work is the **9.0.2**

**Comment by calix** [comment]
Same issue here on 9.2.1.

**Comment by Dinkelborg** [comment]
Same here as well when I started the project this wasn't an issue now suddenly I get this error

**Comment by mk0116** [comment]
same here.
https://github.com/react-native-community/react-native-webview/blob/694b07faa89e19de793c2a90985b9affbeaf28e5/src/WebView.android.tsx#L81
this doesn't properly generate messaging handler name.
Not sure why though.

**Comment by rmatos1** [comment]
Here

> 
> 
> Same here as well when I started the project this wasn't an issue now suddenly I get this error

It happened the same with me. Last week it was working as the expected and now it started to show this error after I started some tests.

**Comment by leoxiaoping** [comment]
+1  "react-native-webview": "^9.4.0",

**Comment by Yozine** [comment]
I updated react-native-webview from 8.0 to the lates and everything seemed in order. 
This error started popping up for me after then updating another package.

**Comment by troymdowd** [comment]
We are also getting this same issue.  9.4.0

**Comment by calix** [comment]
> We are also getting this same issue. 9.4.0
> 
> I tired rolling forward to 10.2.3 but I had an issue trying to build. I will investigate that further as that may be a dependency issue in my project.
> 
> Rolling back to 9.0.2 made everything work.

I can also confirm that rolling back to 9.0.2 solved the issue.

**Comment by daltonwignall** [comment]
Adding to the list that I encountered this issue on `10.2.3` for Android and rolling back to `9.0.2` fixed the issue

**Comment by troymdowd** [comment]
Version 9.0.2 seems to be the standard workaround, but there is now a moderate vulnerability in a dependency of this version of the package, so I would like to update to get my audits cleared.  

I took a deeper dive in the current latest (v10.3.2).  Below is where the issue is presenting itself as noted by @mk0116 .  

> same here.
> https://github.com/react-native-community/react-native-webview/blob/694b07faa89e19de793c2a90985b9affbeaf28e5/src/WebView.android.tsx#L81
> 
> 
> this doesn't properly generate messaging handler name.
> Not sure why though.

The messagingModuleName is undefined when is is trying to register with the BatchedBridge.  I can only debug so deep against the node_module package and I'm not catching when in the app lifecycle this is actually set.  

![image](https://user-images.githubusercontent.com/22801562/88132131-b7ff5980-cbac-11ea-9083-19f5973bc22e.png)

I've forked and cloned this to try and replicate locally, but so far I haven't been able to build the project due to a pathing issue.  I'm probably missing a setting.  
![image](https://user-images.githubusercontent.com/22801562/88132503-a7031800-cbad-11ea-9e0f-5730f14cd0a9.png)

**Comment by troymdowd** [comment]
I upgraded to latest (10.9.0) and I am still experiencing this error from my application.  

I forked the repo last month and attempted to replicate the error by adding in an example using the exact same postMessage/onMessage process I use in my app, but my local build of the library works wonderfully.  

I have it on my worklist after some other projects to attempt to use the forked copy in my app to replicate the error there.  

This is the postMessage/onMessage methods working correctly in the weview example app using the exact same code as in my own app.  
![image](https://user-images.githubusercontent.com/22801562/93839795-0e941d00-fc5c-11ea-9b8a-2d419fe9cd4c.png)

**Comment by stealth-grid** [comment]
I'm also facing same issue, still searching for solutions.

**Comment by kj800x** [comment]
still searching for solutions. @github-actions reopen.

This issue is not fixed. I was able to reproduce this when trying to use [react-native-zss-rich-text-editor](https://github.com/wix/react-native-zss-rich-text-editor) with `react-native-webview@latest`. Ideally I would not like to downgrade to 9.0.2 if there are vulnerabilities.

**Comment by hkar19** [comment]
I also encountered this issue on react-native-webview 11.0.2

**Comment by vadim312** [comment]
I also got this issue on react-native-webview@11.2.3

**Comment by hkar19** [comment]
can anyone please reopen this issue?

**Comment by vgm8** [comment]
Im having the same issue with RN 63.4 and react-native-webview 11.2.3. Any idea how to solve it?

**Comment by gabpaet** [comment]
I am also experiencing this issue, I'm using RN 0.64.2 and react-native-webview 11.14.0

**Comment by charlesYun** [comment]
I also encountered this problem in this version, "react-native webview": "^11.14.2

**Comment by charlesYun** [comment]
Switching to 9.0.2 won't work either

**Comment by Saswat689** [comment]
still causing the issue in version "react-native-webview": "^13.8.4" with expo and react native youtube iframe
