### ISSUE TITLE
Windows Start error

### ISSUE THREAD

**Issue by nrtszr** [react-native-webview/react-native-webview#1514]
Hi,

react-native run-android

Result:

```
Jetifier found 2106 file(s) to forward-jetify. Using 12 workers...
info Starting JS server...
error ENOENT: no such file or directory, open 'undefined/src/main/AndroidManifest.xml'. Run CLI with --verbose flag for more details.
Error: ENOENT: no such file or directory, open 'undefined/src/main/AndroidManifest.xml'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at buildAndRun (D:\mobilprojeler\react-native-webview-master\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:163:41)
    at D:\mobilprojeler\react-native-webview-master\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:147:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (D:\mobilprojeler\react-native-webview-master\node_modules\@react-native-community\cli\build\index.js:186:9)
```

How fix it?

**Comment by troymdowd** [comment]
I am getting the same error.  When doing a `yarn start:android`.

`error ENOENT: no such file or directory, open 'undefined/src/main/AndroidManifest.xml'. `

It looked like a settings issue with the appName/appFolder that is normally passed in through the react-native.cong.js file.  So I tried running it by passing the correct path directly to run-android. 

`npx react-native run-android --appFolder example/android/app`

I am getting the same errors, this time with a path in the error message that actually resolves to the AndroidManifest.  I know this file exists because I can click on the error message and open it.

`error ENOENT: no such file or directory, open 'example/android/app/src/main/AndroidManifest.xml'.`

Perhaps this is a CLI issue?

Steps to reproduce:
1. Clone the repo to a clean directory
2. `yarn install`
3. `yarn start:android`

These are the versions in the `package.json`.
```
"devDependencies": {
    ...
    "@react-native-community/cli": "^4.8.0",
    "@react-native-community/cli-platform-android": "^4.8.0",
    "@react-native-community/cli-platform-ios": "^4.8.0",
    ...
    "react": "16.11.0",
    "react-native": "0.62.2",
    ...
}
```

**Comment by troymdowd** [comment]
I am building this in Windows 10, and there seems to be two issues.

One is a problem with the version of metro-config (v0.56.4, I think) used with the project and recent versions of Node (I'm on v12.18.3). Metro-config contains a bad RegEx and causes metro to fail.  
**Issue**: https://github.com/facebook/metro/issues/453 
**Temporary Workaround**: https://github.com/facebook/metro/issues/453#issuecomment-562093994

The other problem is with the args passed to run-android.  The appFolder arg is calculated to be the string `"undefined"`.  I can't tell where this is coming from when debugging yet.
**Issue**: undetermined
**Temporary Workaround**: My quick workaround for this is to start it this way `npx react-native run-android --appFolder app` which works.  

_Note_: The `--appFolder` flag is deprecated, and it directs you to make changes to the `react-native.config.js` file.  You can try other options with the `react-native.config.js` file to pass the right values, but I haven't found them yet.
