### ISSUE TITLE
Cross-site Tracking (IOS)

### ISSUE THREAD

**Issue by Onreg** [react-native-webview/react-native-webview#1531]
**Bug description:**
According to documentation, there is props `thirdPartyCookiesEnabled` which is responsible for enabling/disabling third-party cookies on Android, on IOS third-party cookies is enabled by default: [thirdPartyCookiesEnabled
](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#thirdpartycookiesenabled) 
I've found a website that can check third-party cookies in the browser: [check third-party cookies](https://whatismybrowser.com/detect/are-third-party-cookies-enabled). So If I set `thirdPartyCookiesEnabled` WebView in Android application works as I expected, the website shows that third-party cookies are enabled. But WebView in IOS application shows that third-party cookies aren't enabled.

Safari browser by default also doesn't accept third-party cookies, but in the settings, there is a param: prevent Cross-site Tracking if I turn in off Safari will start to accept third-party cookies.

Tested it on Simulator iPhone 11 (13.4)

**To Reproduce:**

```
<WebView source={{uri: 'https://whatismybrowser.com/detect/are-third-party-cookies-enabled'}}
         domStorageEnabled={true}
         thirdPartyCookiesEnabled={true}/>
```
**Expected behavior:**

WebView IOS accepts third-party cookies in the same way as Android.

Mybe related question (without correct answer):  [thirdPartyCookiesEnabled on iOS](https://github.com/react-native-community/react-native-webview/issues/486)

**Environment:**
 - OS: IOS
 - OS version: 13.4 
 - react-native version: 0.62.2"
 - react-native-webview version: 10.3.2

**Comment by e3bmo3ty** [comment]
any solution here ? .... i have the same issue  setting "thirdPartyCookiesEnabled={true}"  is not working on iOS

**Comment by mit4dev** [comment]
having the same problem on iOS, setting "thirdPartyCookiesEnabled={true}" won't work

**Comment by mohsinOngraph** [comment]
@e3bmo3ty @mit4dev @Onreg  Any update on this i am facing the same issue

**Comment by ptrckqnln** [comment]
Same problem here.

**Comment by nickviragdesign** [comment]
This seems to be related to the WebKit feature, Intelligent Tracking Prevention (ITP). I found that when I add **NSCrossWebsiteTrackingUsageDescription** to the info.plist file, this triggers a switch to appear in the application's device settings. The switch label is "Allow Cross-Website Tracking." After setting this to switch to TRUE, third party cookies began working as expected in iOS 14.

The problem I'm experiencing now is that I am unsure how to programmatically check the state of this switch from within the app. I need to know the state of the switch in order to decide whether or not the user can successfully authenticate. The app relies on cookie storage in order to authenticate from within the webview (I don't have any control over the client's authentication method). WebKit mentions that you can use `document.hasStorageAccess()`, but this always returns true, regardless of the state of the switch. So it seems to be highly inaccurate.

https://stackoverflow.com/questions/64897054/using-nscrosswebsitetrackingusagedescription-to-request-user-disable-itp-for-wkw

**Comment by lucasroca** [comment]
Has anyone got any further with this issue? I've tried @nickviragdesign's suggestion but still not working on iOS 14.2
When I open https://whatismybrowser.com/detect/are-third-party-cookies-enabled in iOS Safari, it says third party cookies are enabled, but aren't when I open the same URL in a WebView. I have `thirdPartyCookiesEnabled`, `domStorageEnabled` and`sharedCookiesEnabled` all set to true. Also the native switch generated by `NSCrossWebsiteTrackingUsageDescription` is enabled.
I'm not sure what else to try. Any help is much appreciated.

I'm using:
- react-native: 0.63.4
- react-native-webview: 11.2.3

**Comment by matteodanelli** [comment]
@lucasroca I have you same issue. No solution found yey, even if I'm using RN 0.62

**Comment by achieverprince** [comment]
same issue, any update please!!

**Comment by gmyuqi** [comment]
same issue, any update please!!

**Comment by HossamSamir** [comment]
any updates on this yet?
can't do payment integration.

**Comment by JMTeamway** [comment]
Also impacted, hoping some news on the topic ...

**Comment by Carlos199** [comment]
Mismo problema hay alguna solución para habilitar las cookies de terceros en webview para iOS?

**Comment by edgaraskazlauskas** [comment]
Issue is still present

**Comment by pabrn** [comment]
Issue is still present

**Comment by ErickMaeda** [comment]
Well for my website I made it working by adding the `NSCrossWebsiteTrackingUsageDescription` key on my InfoPlist, and enabling it manually on my App Settings.

However, how can we ask for this permission? Before accessing the webview, I would like to ask for this permission, but apparently, the libraries `react-native-tracking-transparency` and `react-native-permissions` does not ask for this permission, the user should activate it manually. 🤔

**Comment by filmic** [comment]
There are plugins available that are capable of redirecting the user to the settings app. You can show a message to the users saying that they will now be redirected and need to allow the tracking.

**Comment by Dr0pG** [comment]
Any updates on this? Still have this issue...
