### ISSUE TITLE
React native android - Unsafe implementation of the HostnameVerifier interface by Google PlayStore

### ISSUE THREAD

**Issue by Sinson48** [react-native-webview/react-native-webview#1778]
Currently, we are facing an issue with HostnameVerifier from a third-party after publishing the app to the Google play store. Kindly help us to find out the issue / any of your customers had faced this issue previously?. We have got an email from Google play store as below.

'We found that your app uses software that contains security vulnerabilities for users. Apps with these vulnerabilities can expose user information or damage a user’s device, and may be considered to be in violation of our Malicious Behavior policy'   'Your app(s) are using an unsafe implementation of the HostnameVerifier interface.'

This app has been in the play store since 2 years.

We need to resolve this before the deadline 1 January 2021.

Please help me sort out this issue.

**Comment by gabriel-tentaculo** [comment]
@Sinson48 I also work in a project that has been around the play store for around 2 years, and it uses this webview for about 6 to 8 months, we have never seen this message before. I got really intrigued by your story because I plan to release new versions of the app soon.

How do you know that this was caused by this library? Did you just added it to your app and then the first time you sent it to review it got rejected or it had this webview implemented before but just got rejected now?
(ps: I'm not one of the maintainers nor contributors here, just a regular user)
