### ISSUE TITLE
Cannot load local images from device data directory

### ISSUE THREAD

**Issue by digitlninja** [react-native-webview/react-native-webview#1786]
Hey guys, 👋🏼
I get this error when trying to load this file as a background-image url() in css/html dynamically.
`Not allowed to load local resource: file:///data/user/0/com.mobileapp/files/Olarm/areas_0_44174.jpg`

![image](https://user-images.githubusercontent.com/12513193/101888083-603aac80-3ba6-11eb-81a1-1cb0c5eac896.png)

I tried adding allowUniversalAccessFromFileURLs + allowFileAccess and the error still persists.

```
<WebView
                ref={webview => webviewRef.current = webview}
                source={{ uri: 'http://localhost:8082' }}
                style={{ marginTop: 20 }}
                onMessage={(event) => NativePigeon.receiver(event, webviewRef)}
                allowUniversalAccessFromFileURLs={true}
                allowFileAccess={true}
            />
```

I went the base64 route and sent those to the webapp. which worked, when I logged out and back in to the app the images were gone.

Please advise urgently. Been stuck on this for weeks!!! It should be something one can do relatively simply as loading uploaded images is part of 90% of apps.

Thanks in advance 🙏🏼

**Comment by tomSawkins** [comment]
Did you ever find the solution to this issue? I'm currently in the exact same boat

**Comment by faizantariq1** [comment]
@tomSawkins  did you find the solution?

**Comment by tomSawkins** [comment]
@faizantariq1 Yes!

So the problem is that you can specify the `source` in 2 ways 
`{ uri: 'https://somewhere.with.html/' }` OR `{ html: '<actual html>', baseUrl: '' }`

If you use the `uri` config it will prevent you from accessing local `file://` url assets however if you use `html` and set a `baseUrl` then within your webview you can reference assets with relative paths `./images/nice.jpg`

Example of mine (rnFS is react-native-fs):
```
{
  html: "html with js inlined",
  baseUrl: 'file://' + rnFS.CachesDirectoryPath
}
```
What that means is if I download images into the `rnFS.CachesDirectoryPath` folder i can refernce them in the webview like `./nice.jpg` and it will load like you'd expect

**Comment by mustvlad** [comment]
Any solution on this yet? I don't see as a good solution to add the HTML instead of the `uri`.

**Comment by linonetwo** [comment]
But using `file://` will prevent `window.indexedDB.databases()` to work. `SecurityError: Failed to execute 'databases' on 'IDBFactory': Access to the IndexedDB API is denied in this context.`

Still have to use `baseUrl: 'http://localhost',` for `window.indexedDB.databases()` and `localstorage`.
