### ISSUE TITLE
Migrate to WebView2 in Windows

### ISSUE THREAD

**Issue by taurheim** [react-native-webview/react-native-webview#1848]
**Is your feature request related to a problem? If so, Please describe.**

EdgeHTML (the "old edge" rendering engine, used in this library) has many quirks and unsupported features, and will stop being supported by Microsoft on March 9, 2021 (https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge). This library renders using WebView, which uses EdgeHTML as a rendering engine. As end of life happens for this rendering engine, sites rendered using this webview may not function.

**Describe the solutions you came up with**

I believe this can be done by using https://docs.microsoft.com/en-us/microsoft-edge/webview2/, which uses the Edge chromium rendering engine.

**Additional context**

**Comment by asklar** [comment]
This will require the module moving to use WinUI 3 as well, so really there need to be two separate packages: one for apps targeting system XAML + WebView and one for apps targeting WinUI 3 + WebView2.

**Comment by Byron1990** [comment]
Enviado desde mi HUAWEI Y9 Prime 2019-------- Mensaje original --------De: Alexander Sklar <notifications@github.com>Fecha: lun., 1 feb. 2021 04:28Para: react-native-webview/react-native-webview <react-native-webview@noreply.github.com>CC: Subscribed <subscribed@noreply.github.com>Asunto: Re: [react-native-webview/react-native-webview] Migrate to WebView2 in Windows (#1848)
This will require the module moving to use WinUI 3 as well, so really there need to be two separate packages: one for apps targeting system XAML + WebView and one for apps targeting WinUI 3 + WebView2.

**Comment by exotexot** [comment]
Is there any statement from the react-native-webview maintainers of how likely it is to see WebView2 as part of the react-native-webview library?

I hate to say it, but the original WebView component which is implemented as of now for Windows, really is a disgrace.

**Comment by asklar** [comment]
Bump

**Comment by emanuelmartin** [comment]
Any news on this?

**Comment by asklar** [comment]
We still want to do this. No fixed timeline on when this might be possible yet.

**Comment by sw-tt-shirinafrozansari** [comment]
@asklar We are also looking forward to implement WebView2 in our React Native App.
Looking forward for an early update on this from the community.

**Comment by exotexot** [comment]
Any updates here?

**Comment by asklar** [comment]
Nothing to share yet but this is still on our radar.

**Comment by asklar** [comment]
Update: we are now discussing bringing WebView2 to UWP via microsoft/microsoft-ui-xaml#5610

**Comment by tero-paananen** [comment]
I had this same issue before https://github.com/react-native-webview/react-native-webview/issues/1703

**Comment by WilliamABradley** [comment]
The latest prerelease backported Webview2 to WinUI 2: https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.7.0-prerelease.210827001

**Comment by chiaramooney** [comment]
**General Spec for Adding WebView2 to WebView community module**

**What is the goal of this feature work?** 
Give developers access to both the WinUI WebView and WebView2 controls via the WebView community module. Solution will allow developers to use both WebView and WebView2 within the same application, switch an instance of the WebView component between the WinUI WebView and WebView2 controls at runtime, and requires minimal JSX changes to the original WebView API.
With these changes, we will continue to provide support for original WebView control in this community module, due to deploy limitations with WebView2. WebView2 can only target Desktop. WebView2 also currently does not have an API for projecting a WinRT object, but this feature work is in progress.

**How will this feature work be executed?**
_Toggling Between the WebView and WebView2 Control_
The toggle from WebView to WebView2 will be handled from the JavaScript. In this solution, a Windows specific prop would be added to the WebView component called `useWebView2`. Next, a separate native module for WebView2 based off of the original WebView code is created. Now we have two windows projects. Then both modules are imported to the JavaScript and, based on the value of the `useWebView2` prop, which defaults to false if not specified, then the ReactNativeWebView or ReactNativeWebView2 module is returned as the WebView component. With this solution, developers can toggle between WebView and WebView2 at runtime by adjusting the value of the useWebView2 prop. Note this solution matches the design of the react-native-datetimepicker community module which provides both the TimePicker and DateTimePicker components. 

_The ReactNativeWebView2 Native Module_
We have exposed the WebView2 control through WinUI 2.7-prerelease. Currently, WebView (like most native modules) gets its copy of WinUI through the React Native Windows app that it's added to. And the app gets its WinUI version from RNW (unless the WinUI override is used). We need to configure the WebView module similar to react-native-xaml where the module can declare a dependency on a specific WinUI version, so that the module can have access to the WebView2 control.
The source for the ReactNativeWebView2 native module will be based off of the source for the original ReactNativeWebView native module. There will need to be a few adjustments made to the code such as swapping out the WebView control type for WebView2, renaming files and classes, and adjusting functionality to account for behavior that is not supported for the WebView2 control.

**Diagrams**
_Original Module Structure_
![image](https://user-images.githubusercontent.com/34109996/145873157-e836191d-c16f-4055-8223-d625b16f65cb.png)
_Proposed Module Structure_
![image](https://user-images.githubusercontent.com/34109996/145873177-2535d39b-9f60-420d-923b-69b81e8b7ef4.png)

**Comment by chiaramooney** [comment]
> Hello, How to you configure your RNW project in order to use a preview 2.7.0 of Microsoft.UI.Xaml ? If I upgrade the package Microsoft.UI.XAML with nuget on the project, it will first uninstall version 2.6.0, then install the preview.
> 
> But may projects in react native windows solution (SLN) depends on version 2.6.0, thus the compilation fails as this dependency is not met.
> 
> How can I either maintain both versions in packages, or replace every where the depency to point to the previous version?
> 
> Thanks for your support, Chris
 @kristofb 

You'll want to edit the ExperimentalFeature.props file of your app project. Add `<WinUI2xVersion>MUX Version Here</WinUI2xVersion>` to this file and then restore your Nuget packages.

See https://microsoft.github.io/react-native-windows/docs/customizing-sdk-versions for more info.

**Comment by tero-paananen** [comment]
We need working post message functionality also for WebView2. I think may this be problem to get it https://github.com/MicrosoftEdge/WebView2Feedback/issues/292 or is there another way then to implement it...

**Comment by asklar** [comment]
🎉🥳
