### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCWebView

### ISSUE THREAD

**Issue by nandukalidindi** [react-native-webview/react-native-webview#1893]
**Bug description:**
To implement the OAuth dance flow for a Twitter login I made use of `react-native-webview` and it's `onNavigationChange` however, there is a `react-native-linkedin` dependency in my project for LinkedIn login which also seems to be using `react-native-webview`. This is resulting in the mentioned error. Tried installing same versions or `react-native-webview`, cleaned cache, reinstalled dependencies but nothing worked.

There is a similar issue which was closed due to inactivity https://github.com/react-native-webview/react-native-webview/issues/1083. Please suggest.

And matching the versions across all dependencies that use `react-native-webview` could get impossible as the dependency number goes up. 

**To Reproduce:**
Install `react-native-linkedin` and `react-native-webview` in the same project

I tried installing the `react-native-linkedin: 2.1.0`with `react-native-webview: 7.0.5` since `7.0.5` is the webview version in `react-native-linkedin`'s `2.1.0` package 
https://github.com/xcarpentier/react-native-linkedin/blob/v2.1.0/package.json

**Screenshots/Videos:**
https://user-images.githubusercontent.com/4492228/109238798-2db25000-77a2-11eb-9647-2aa608bae153.png

**Environment:**
 - OS: iOS, Expo
 - react-native version: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
 - react-native-webview version: 7.0.5

**Comment by wsultani** [comment]
This is still happening with:
"eas-cli": "^3.8.1",
"expo": "~48.0.9", 

ERROR  Invariant Violation: Tried to register two views with the same name RNCWebView, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
› Stopped server

npm ls react-native-webview
├─┬ react-native-instagram-login@2.0.5
│ └── react-native-webview@11.26.1
└─┬ react-native-linkedin@2.1.1

**Comment by obiofiong** [comment]
Any Definite solution for something like this?
