### ISSUE TITLE
Android | onLoadEnd, onLoad, onLoadStart not called on url changes/Navigation

### ISSUE THREAD

**Issue by Yahyaali1** [react-native-webview/react-native-webview#1900]
**Bug description:**
After the web url is initially loaded, if the user tries to navigate on any of the pages on same domain, following events are not registered "**onLoadEnd, onLoad & onLoadStart**". This seems to be working fine on iOS. This seems like any issue with websites that are using client side rendering. As observed with https://www.amazon.com it performs as expected. 

**To Reproduce:**

[I have added an expo snack code](https://snack.expo.io/@yahya1/bad-stroopwafels). Similar behavior is observed with following websites:

- https://www.target.com
- https://www.samsclub.com

**Expected behavior:**

onLoadEnd, onLoad, onLoadStart should be registered as user navigates through website after initial load. 

**Environment:**
 - OS: Mac
 - OS version: 11.1
 - react-native version: 0.63.3
 - react-native-webview version: 11.2.3
 - Test Device: Pixel 2XL

**Comment by Yahyaali1** [comment]
Here is another bug around [similar issue](https://github.com/react-native-webview/react-native-webview/issues/1510)

**Comment by tschanz-pcv** [comment]
Hey, I ran into the same issue. On iOS it works but on Android it just doesn't emit the events. I'm only really interested in the `onLoadStart` event so I created this little `patch-package` hack compatible with version `10.7.0`:

```
diff --git a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
index a5a1850..b83c9b6 100644
--- a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
+++ b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
@@ -808,6 +808,15 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
       return this.shouldOverrideUrlLoading(view, url);
     }

+    @Override
+    public void doUpdateVisitedHistory(WebView view, String url, boolean isReload) {
+      dispatchEvent(
+        view,
+        new TopLoadingStartEvent(
+          view.getId(),
+          createWebViewEvent(view, url)));
+    }
+
     @Override
     public void onReceivedSslError(final WebView webView, final SslErrorHandler handler, final SslError error) {
         handler.cancel();

```

What it does:
- Also overrides `doUpdateVisitedHistory`: https://developer.android.com/reference/android/webkit/WebViewClient#doUpdateVisitedHistory(android.webkit.WebView,%20java.lang.String,%20boolean) the documentation states: `Notify the host application to update its visited links database.`
- Trigger `onLoadStart` event with the received URL
- It's API lvl 1 so it should work where ever this plugin works

This is not very clean because:
- It doesn't pass on the `isReload` boolean, so that won't be part of the generated event
- Triggering an `onLoadStart` might not be the best option, maybe it might be better to have a new listener like `onBrowserHistoryChange` for both iOS & Android
- Doesn't help with the broken `onLoadEnd`

With my extensive tests of exactly 1 Website and only exactly 1 user flow on there I can't say if this will fuck up on other pages but at least in my use-case it looks like it behaves the same as on iOS with this. Just be aware that you `onLoadStart` may be called multiple times with the same URL; but that was the case on iOS for me anyways.

I don't have the time and nerves at the moment to get to know the code of this plugin better to create a clean PR so this is all I can provide.

Hope it helps you :)

**Comment by paulg0614** [comment]
Seems to be called on android if I set 
setSupportMultipleWindows={false}
