### ISSUE TITLE
Windows CI is broken

### ISSUE THREAD

**Issue by asklar** [react-native-webview/react-native-webview#1930]
**Bug description:**
The Windows CI has been broken for 5 months, we should clean things up and get it back up and running.

**To Reproduce:**
Send a PR, Windows build is broken going back to November-ish 2020
Looks like this started with PR #1623 

**Expected behavior:**
Windows CI passes

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/22989529/111890831-a3c56380-89aa-11eb-8992-23eaa69964d8.png)

**Comment by asklar** [comment]
@cglein FYI

**Comment by NickGerleman** [comment]
I expect there will need to be continuous contribution to keep Windows CI working correctly. I know there was been some internal discussion about this before, since maintenance hasn't been super hands-on since the original contribution.

Some of the CI breaks that RNW sees that would apply to modules as well:
- Visual Studio Breaks (and associated patch releases)
- Major version upgrades for WIndows, to keep CI working
- RNW build instability on less powerful machines

**Comment by asklar** [comment]
Should be back to working
