### ISSUE TITLE
Typescript environment will prompt an error when using source?.uri

### ISSUE THREAD

**Issue by Bruce-zxy** [react-native-webview/react-native-webview#2019]
**Bug description:**
When I use the source?.uri attribute in the typescript environment, the typescript environment will prompt me that the uri attribute does not exist on the WebViewSource type and the WebViewSourceHtml type. Then I checked the WebViewSource type in lib/WebViewTypes.d.ts\<line:143\> in the npm source code. I found that the WebViewSource type used Union Types instead of Intersection Types when combining the WebViewUri type with the WebViewHtml type. It may cause this problem I encountered.
When I change the type combination method from | to &, the typescript environment will no longer prompt errors.

Docs:[Union Types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types)
![image](https://user-images.githubusercontent.com/22904758/119754623-5f3ad480-bed3-11eb-85c3-e7a520a58a06.png)

**Expected behavior:**
The typescript environment will not prompt an error when referencing source?.url.

**Screenshots/Videos:**
Before modification:
![image](https://user-images.githubusercontent.com/22904758/119753493-737dd200-bed1-11eb-8073-fccf66ba10d2.png)
After modification:
![image](https://user-images.githubusercontent.com/22904758/119753911-264e3000-bed2-11eb-90c6-f1b9d9fffcdf.png)

**Environment:**
 - react-native version: 0.64.1
 - react-native-webview version: 11.6.2

**Comment by TheAlmightyBob** [comment]
> Why not & but |

Because the `WebView` expects _either_ one type or the other. Using `&` would mean that it requires _both_ the `html` and `uri` properties to be defined, which wouldn't make sense.

The trick here is that this isn't using [discriminated unions](https://basarat.gitbook.io/typescript/type-system/discriminated-unions), so there's not an easy way later for Typescript to know which type was actually used. A discriminating field could be added, but that creates a bit of a burden for the most common case where people are just passing in these props and not trying to read them like you're doing. As a workaround, you _could_ just cast it (since you're checking the existence of `uri` already, rather than assuming that it's defined)...

```typescript
if (!(props.source as WebViewSourceUri)?.uri) {
```
---

In terms of changes to the actual types, I've recently been experimenting with the technique of using `never` to allow telling Typescript about a property that _shouldn't_ be there (there are various blogs and StackOverflow posts about this, I didn't come up with it). So, theoretically, there could be something like:

```typescript
export interface WebViewSourceUri {
    /**
     * The URI to load in the `WebView`. Can be a local or remote file.
     */
    uri: string;
    /**
     * The HTTP Method to use. Defaults to GET if not specified.
     * NOTE: On Android, only GET and POST are supported.
     */
    method?: string;
    /**
     * Additional HTTP headers to send with the request.
     * NOTE: On Android, this can only be used with GET requests.
     */
    headers?: Object;
    /**
     * The HTTP body to send with the request. This must be a valid
     * UTF-8 string, and will be sent exactly as specified, with no
     * additional encoding (e.g. URL-escaping or base64) applied.
     * NOTE: On Android, this can only be used with POST requests.
     */
    body?: string;
    html?: never;
}
export interface WebViewSourceHtml {
    /**
     * A static HTML page to display in the WebView.
     */
    html: string;
    /**
     * The base URL to be used for any relative links in the HTML.
     */
    baseUrl?: string;
    uri?: never;
}
```

So that would still forbid setting both `html` and `uri`, but it would allow your code to query the presence of `uri` without casting.

It's a bit hacky and not-quite-intuitive though, so I'm not sure if it's desirable for the official `react-native-webview` types...
