### ISSUE TITLE
Cannot read from localhost or local file after Windows OS update (21H1 19043.1052)

### ISSUE THREAD

**Issue by tero-paananen** [react-native-webview/react-native-webview#2049]
After updating to latest Windows OS version **21H1 19043.1052** stops WebView to read `localhost` file. Also `file://` url kills the WebView. 

`ms-appdata:///local/` seem to work.

**Environment:**
 - OS: Windows 10
 - OS version: 21H1
 - OS build: 19043.1052
 - react-native-windows version: 0.62.22 
 - react-native-webview version: 10.10

**Comment by tero-paananen** [comment]
Issue is in all these Windows OS versions

Release Date: 6/8/2021
Version: OS Builds 19041.1052, 19042.1052, and 19043.1052

**Comment by juhasuni** [comment]
WebView seems to partially block HTTP requests to non-standard ports after the recent Windows update. E.g. a request to `http://localhost:5612` receives a response but apparently without any header information, which is why the WebView considers the response to be plain text and thus doesn't try to render HTML but simply prints the source code. The same request to standard `80` port works without issues.

**Comment by asklar** [comment]
Several issues might be at play here, none of which seem like a recent OS regression, though.
1. re: the restriction on localhost, that can be related to network isolation:
   - https://docs.microsoft.com/en-us/previous-versions/windows/apps/dn640582(v=win.10)?redirectedfrom=MSDN
   - https://github.com/microsoft/ProjectReunion/issues/113
   - https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2226
 2. the app might be missing the private network capability in its manifest: https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

I'm not sure about why a response from a non-standard port would return without header information, did this use to work differently in prior OS releases? I'd be surprised if this changed.

**Comment by juhasuni** [comment]
@asklar , we've been using localhost access previously (from WebView) without any issues. So we've adjusted our app capabilities etc. to make it work a long ago. We also tested this against older version of our app to rule out the possibility that some of our own recent change would have caused the issue. The issue started just after the recent OS update last week.

I'll try to run some other investigations on this topic, like if the non-standard ports are blocked also when accessing content outside localhost.

**Comment by juhasuni** [comment]
Some of our test findings regarding to the `source` prop used with the WebView:

- `<VebView source={{uri: 'ms-appx-web://.../index.html'}} ...`  - requests to `http://localhost:any-port` within the WebView work 
- `<VebView source={{uri: 'file://.../index.html'}} ...`  - WebView crashes
- `<VebView source={{uri: 'ms-appdata:///local/.../index.html'}} ...`  - WebView renders HTML but any requests within WebView to `http://localhost:non-standard-port` fails (according to Edge DevTools the requests are missing response headers, but I'm not sure that can be trusted)
- `<VebView source={{uri: 'http://localhost:non-standard-port/.../index.html'}} ...` - WebView doesn't render the HTML but simply prints the code (we assume it is missing response headers and considers the content to be text/plain)
- `<VebView source={{uri: 'http://localhost:80/.../index.html'}} ...` - WebView renders the HTML perfectly

The internal server we run here doesn't change its behavior in any way based on the port used (unless 443 of course).

**Comment by asklar** [comment]
@juhasuni is it possible that there was a network isolation exception set up which enabled the app to work, and the update to the new Windows version didn't carry it forward? Can you try enabling the exception as described in the docs I linked above?

**Comment by juhasuni** [comment]
> Can you try enabling the exception as described in the docs I linked above?

Thanks, I'll check that one next.

**Comment by juhasuni** [comment]
@asklar , you meant the `loopback exemption`? We're not using that, because we don't need inter-communication with other apps and besides it is only meant for dev releases/sideloading.

**Comment by juhasuni** [comment]
Just to clarify, the `localhost` web server in our case is running within the same app. That's why it doesn't (shouldn't) require any loopback hacks.

**Comment by juhasuni** [comment]
The issue with accessing `http://localhost:non-standard-port` has been resolved and it is indeed due to missing headers, but the problem is at our end.

The hypothesis here is, that Windows WebView component prior to last updates was running in some kind of compatibility mode, where it guessed the `Content-Type` of the response if the header wasn't present. After the update the hypothetic compat mode is only active if the port is standard 80.

Then the issue with file:// URLs seems to be a real one. However, opening content in WebView using `file://` URLs is an undocumented feature (not mentioned anywhere in official MS docs). It should be probably stated here as well, that it is not recommended to open content from file URLs (`ms-appdata://` is the proper format).

**Comment by asklar** [comment]
Yes I imagine accessing file:// urls wouldn't work inside the uwp appcontainer.
You can use ms-appx-web, ms-appdata, or http/https. See the webview samples [here](https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/XamlWebView/) which show accessing appx-packaged files as well as content through `UriToStreamResolver` if you need to create content on the fly.
