### ISSUE TITLE
WebView content not show fully in Landscape mode

### ISSUE THREAD

**Issue by gopikasireddy202** [react-native-webview/react-native-webview#2120]
HI,

When I rotate my mobile screen to Landscape mode then Webview content not showing fully.

Thank you.

**Comment by yorickshan** [comment]
same issue

**Comment by SufianBabri** [comment]
@gopikasireddy202 @yorickshan have you found a solution to this issue?

**Comment by gkasireddy202** [comment]
No.

**Comment by SufianBabri** [comment]
The occurs because (to what I understand) of the change in zoom value (in my case, rotating the device to landscape and back to portrait will show a zoomed-out view).

It seems like an issue with the `WKWebView` which this library is internally using on iOS.

I found [this SO thread](https://stackoverflow.com/questions/35042412/wkwebview-displays-content-wrong-after-orientation-change) on this issue.

**Comment by albert17** [comment]
@SufianBabri Thanks for posting that link!

What did you end up doing? Injecting the JS call `webView.evaluateJavaScript("location.reload();", completionHandler: nil)` ?

**Comment by SufianBabri** [comment]
@albert17 yes the solutions are for WKWebView, and this library uses it (WKWebView) on iOS.

Someone who is more proficient in iOS development can look into the issue in light of the mentioned SO thread, and hopefully be able to fix the issue.

**Comment by ekko2665** [comment]
> @albert17 yes the solutions are for WKWebView, and this library uses it (WKWebView) on iOS.是的，解决方案适用于 WKWebView，此库在 iOS 上使用它 （WKWebView）。
> 
> Someone who is more proficient in iOS development can look into the issue in light of the mentioned SO thread, and hopefully be able to fix the issue.更精通 iOS 开发的人可以根据上述 SO 线程来研究问题，并希望能够解决问题。

but i am Android error ， ios is right。 so there is no solutions?
