### ISSUE TITLE
When placed within a KeyboardAvoidingView it seems to avoid the keyboard twice

### ISSUE THREAD

**Issue by alfredvaa** [react-native-webview/react-native-webview#2149]
**Bug description:**

When placing the Webview within a KeyboardAvoidingView, the web page viewed gets some extra padding at the bottom. The green area in the screen shot is 100vh in height, so without the keyboard showing it is not possible to scroll the page. When the keyboard appears, the page is getting scrollable when it should not be.

I could sort of solve this issue by not using a KeyboardAvoidingView, but I guess that would cause other issues later on if I actually need that in place. My guess is that this is related to a known issue with Safari for Ios which seems to not resize the viewport correctly when opening the keyboard. I am not sure if my issue is even solvable by react-native-webview but it would be great to discuss possible workarounds anyway.

**To Reproduce:**

```
    <SafeAreaView style={{ flex: 1 }}>
      <KeyboardAvoidingView
        style={{ flex: 1 }}
        behavior={Platform.OS === "ios" ? "padding" : "height"}
      >
        <WebView
          style={{
            flex: 1,
            borderColor: "pink",
            borderWidth: 1,
            borderStyle: "solid",
          }}
          source={{ uri: "http://localhost:3001" }}
          hideKeyboardAccessoryView
          bounces={false}
        />
      </KeyboardAvoidingView>
    </SafeAreaView>
```

**Expected behavior:**

The page should not scroll.

**Screenshots/Videos:**

<img width="466" alt="image" src="https://user-images.githubusercontent.com/10890307/131386828-bdcb28da-363d-4760-b609-9dcfd328781a.png">
Screen shot when the view is scrolled to bottom. The grey area is the extra unwanted space.

**Environment:**
 - OS: IOS
 - OS version: 14.7.1
 - react-native version: Expo 42
 - react-native-webview version:

**Comment by TheWirv** [comment]
This is not an iOS-exclusive problem. It also happens on Android where there seems to an arbitrary amount of "grey space"... :/

**Comment by rado196** [comment]
same on ios, the problem still exists.

**Comment by rado196** [comment]
same on ios, the problem still exists.

**Comment by andraderaul** [comment]
Have you tried setting the `scrollEnabled` to `true`?
You can see in the [docs](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#scrollenabled)

**Comment by Logan-FE** [comment]
any fixed on this?

**Comment by Nantris** [comment]
The fix in our case was to set `scrollEnabled` to false. This took waaaaaay too long to track down the cause of. iOS is weird.

**Comment by YlanGarnier** [comment]
issue still exist btw, what happens is the following :

IOS reset the state of `scrollEnable` to false each time you update the dimensions of the webview (which is what happens when keyboard appear and hide with keyboardAvoidingView.

Actually even worse is that it doesn't update the public state, just its inner state, so you can't see it on debug and track it down.

What helped me was to re set explicitly the prop state on each keyboard change : 
```tsx
const [iosWebviewScroll, setIosWebviewScroll] = useState<boolean>(true);
const keyboardDidShow = Keyboard.addListener('keyboardDidShow', () => {
	setIosWebviewScroll(false);
};
const keyboardDidHide = Keyboard.addListener('keyboardDidHide', () => {
	setIosWebviewScroll(true);
	setIosWebviewScroll(false);

};
```

**Comment by vickz84259** [comment]
Hey just wanted to provide additional context. The fix that @Nantris suggested (`scrollEnabled = false`) works with the Legacy Architecture. With React Native 0.76 the New Architecture was turned on by default. This brought back the issue in a new way as stated by @YlanGarnier. 

If you disable the New Architecture, the initial fix of having `scrollEnabled` set to `false` just works.

**Comment by vickz84259** [comment]
On my end I had to implement it like this: 
```javascript
const [scrollEnabled, setScrollEnabled] = useState<boolean>(true);
useLayoutEffect(() => {
    const keyboardEventSubscription = Keyboard.addListener(
      'keyboardDidShow',
      () => {
        if (Platform.OS === 'ios') setScrollEnabled(false);
      }
    );

    return () => {
      keyboardEventSubscription.remove();
    };
  }, []);
```

The `if` is important as calling `setScrollEnabled(false)` on Android will result in the keyboard opening then the whole screen going blank. This could be because on my end we have `KeyboardAvoidingView` disabled on Android.

Also, from my testing since `setScrollEnabled(false)` will only happen once, this is more than enough. The bug doesn't reoccur on subsequent opening and closing of the keyboard.

**Comment by Nantris** [comment]
Oh no... I hadn't realized this might return on the new architecture...

There's another issue about overscroll/bounce I can't easily find right now from mobile, but several people in that thread suggested that the settings weren't working unless they applied them after some delay from when the component initially mounted. 

I wonder if a simple delay approach might work for this also. If so, that might point to a common cause for several issues on iOS.

**Comment by nik0kin** [comment]
I have reproduced this in a Snack: https://snack.expo.dev/@payactiv/smelly-blue-cookie-github-issue?platform=ios

How do I eliminate the green bottom whitespace from showing when the input focused and the keyboard opens?

Disabling scrolling doesn't help me, because I want the user to be able to scroll to read instructions, etc.
