### ISSUE TITLE
Android Webview Err_Content_Decoding_Failed

### ISSUE THREAD

**Issue by meoner** [react-native-webview/react-native-webview#2245]
I am using webview to access website from mobile application. Works perfectly for most websites but I'm getting error on some websites. This error only exists in android. 

(![Error ScreenShot](https://user-images.githubusercontent.com/32526108/142883830-b1cb4622-9995-4e30-b478-568e1c9fcad2.png)

Here my simple WebView Code

`
<WebView
        style={webviewStyle}
        source={{uri: https://www.randomwebsite.com}}
      />`

**Environment:**
 - OS: Android
 - OS version: Android 11
 - react-native version: 0.65.1
 - react-native-webview version: 11.14.1

**Comment by nakulsaini** [comment]
+1

**Comment by ringo-w** [comment]
Still searching for solutions

**Comment by AaronWitter** [comment]
+1

**Comment by mali-tintash** [comment]
was there a solution to this ?

**Comment by akshaykrsharma** [comment]
I encountered a similar problem recently. It turned out that the issue was caused by sharing the build with someone in the US region. Surprisingly, the build worked perfectly there. This leads me to believe that geographical location might play a role in these types of issues. Alternatively, you could try resolving the problem by enabling a VPN and checking if that resolves the situation. It's worth exploring these possibilities to get to the root of the problem.

:)
