### ISSUE TITLE
Camera/Microphone permission not asking? Expo SDK 44

### ISSUE THREAD

**Issue by vinayn-mend** [react-native-webview/react-native-webview#2443]
**Bug description:**
The webview is not asking for camera/microphone permission. The source url which is a video visit page has getusermedia() function but still not asking for permissions hence it is stuck in a loading screen. But if I try to reload the url it is asking for permission on iOS but not for android

**To Reproduce:**
```
const [url, setUrl] = useState(props.route.params.url);

const handleWebViewNavigationStateChange = (url: string = '') => {
    if (
      (url && url.includes(PORTAL_DASHBOARD_URL)) ||
      url === PORTAL_DASHBOARD_URL
    ) {
      setUrl(LOGOUT_URL); //ToDo: Remove if not needed
      navigation.navigate('VirtualVisit');
    }
    if (url.includes(PORTAL_VIDEO_URL)) {
      setUrl(url);
    }
  };

 <WebView
     ref={webViewRef}
     source={{uri: url}}
     javaScriptEnabled={true}
     onLoadEnd={(syntheticEvent: WebViewEvent) => {
        const {nativeEvent} = syntheticEvent;
         if (url.includes(CUSTOM_URL)) {
           if (nativeEvent.loading == false && reloadCount <= 1) {
            webViewRef.current?.reload();
              setCount(reloadCount + 1);
             }
           }
          setLoaded(!nativeEvent.loading);
          }}
     onNavigationStateChange={(navigationState: WebViewNavigation) => {
            handleWebViewNavigationStateChange(navigationState?.url);
          }}
     onLoadProgress={(event: WebViewEvent) =>
            handleWebViewNavigationStateChange(event?.nativeEvent?.url)
          }
     allowsInlineMediaPlayback={true}
     mediaPlaybackRequiresUserAction={false}
     originWhitelist={['*']}
     userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"
     onError={(e) => console.log('error: ', e)}
 />
```

**Expected behavior:**
It should ask for permission normally without any workaround like reloading the url.

**Environment:**
 - OS: Android/iOS
 - OS version: both running latest OS 
 - react-native version: ^0.64.3 (Expo managed workflow Expo version: 44)
 - react-native-webview version: 11.15.0

**Comment by HyunseungLee-Travis** [comment]
@vinayn-mend I tried out a website that asks for microphone/camera permission upon entering website and it seems to work without reloading the page. I asks for permission from expo upon entering website.

I think the problem is the logic is either in `reload()` or `handleWebViewNavigationStateChange()` or `handleWebViewNavigationStateChange()` as the permission asking worked fine without them.

Maybe since the page loaded and reloaded again to ask for permission, there might be an issue with `onLoadEnd()` logic because it reloadeda after loading.

**Comment by vinayn-mend** [comment]
@HyunseungLee-Travis I have updated my question with what's happening inside `handleWebViewNavigationStateChange()` . 

What I'm doing is before navigating to the webview screen, I'm asking for camera/mic permission using **expo-permissions/expo-av** on click of a Connect button and then navigating to a screen where it loads this webview. 

Could you please provide a code snippet of how you asked for permission and all? Also can you provide the website you've tried out ? That would be really helpful

**Comment by HyunseungLee-Travis** [comment]
I used browser's built in `getUserMedia()` api.
It might not be what you wanted, but using `getUserMedia()` works.
Since it's a webview, I find it more easier to ask for permission in the browser rather than use the code in Expo or React Native.

Browser
```
navigator.mediaDevices.getUserMedia({
    video: {
        facingMode: 'environment',
        width: { ideal: 4096 },
        height: { ideal: 2160 },
    },
})
.then((s) => { //Do something with video })
.catch((e) => {
    console.log(e) // Log errors
});
```

One thing I don't understand is why would you want to use a camera in React Native code and then navigate to website? If you want to do anything with videos, shouldn't you be trying to code the video component in website and then asking for permission in website rather than Expo?

I might not have understood your itentions of using camera.

I prefer this way if I want to use the cameras.

**Comment by vinayn-mend** [comment]
@HyunseungLee-Travis Well I thought it's required to allow camera/mic permission in order to access it. 

Yes, here also the browser's built in api is used. And I'm getting the permission request alert but only for iOS. And that too after doing the reload programmatically like I've shown above. But for Android, it's not even asking for any permission after reload and the website is going to an else case page where it shows the user that
![Microphone disabled/unavailable - Android](https://user-images.githubusercontent.com/95361842/163752194-b4824cca-17d6-4490-9a06-3373a28112b6.png)

**Comment by vinayn-mend** [comment]
Any update on this ? I was able to open the website on Chrome mobile browser and it is asking for camera/mic permission properly. If it is working properly on a browser, what'll be the reason it is not working inside a webview ?  @HyunseungLee-Travis

**Comment by ratz6** [comment]
Same for me . We are building a Video conferencing in react and using the component is mobile with react native webview. The camera and mic works on iOS smoothly. But on some android devices I'm not able to toggle between Back Cam and front Cam and on some android devices, the camera itself is freezing. This was the sample URL we used for gUM 
https://simpl.info/getusermedia/sources/

**Comment by henlamk** [comment]
Could you find a solution? @ratz6 @vinayn-mend
