### ISSUE TITLE
Microsoft.Web.WebView2.Core.h No such file or directory

### ISSUE THREAD

**Issue by gangli66** [react-native-webview/react-native-webview#2563]
When I use react-native-webview for my react-native-windows project, there is an error while compiling. It seems that in the webview pch.h file, it needs winrt/Microsoft.Web.WebView2.Core.h after the react-native version 0.68.0. However, I have not seen there is a file named this in GenerateFiles directory. So it reports the error describing that No such file or directory or Can not open source file in VS2019. Can I gain your help to solve the issue? Thank you.
**To Reproduce:**

1. Coding my project using <WebView> in a React Native platform.
2. execute "yarn" and "yarn add react-native-windows"
3. execute "npx react-native run-windows"
4. it will take a long time and then display the issue.
**Expected behavior:**

compiling success.
**Screenshots/Videos:**

**Environment:**
 - OS: Win10
 - OS version: 21H1 19043.1766
 - react-native version: 0.68.2
 - react-native-webview version: 0.68.5

**Comment by asklar** [comment]
@chiaramooney  I believe you are looking at this with the opt-in work, right?

**Comment by chiaramooney** [comment]
This is because you aren't specifying WinUI 2.8.0-prerelease in your ExperimentalFeatures file, see here: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Getting-Started.md#3-webview2-support

We have a PR out now to enable opting into using this WinUI version for v68 apps, but currently to get your module to build you will need this WinUI version if your app is v68+.
