### ISSUE TITLE
[Android] ScrollView not working properly after WebView is pressed

### ISSUE THREAD

**Issue by mk-nickyang** [react-native-webview/react-native-webview#2565]
**Bug description:**
I was trying to create a simple screen where it has a `WebView` inside a `ScrollView`, and the fixed header shrinks on scroll. It works perfectly on IOS, but on Android, as soon as I press inside the `WebView`, the `ScrollView` will not be working, cannot scroll down whatsoever.

**To Reproduce:**
1. Clone repo: https://github.com/mk-nickyang/react-native-webview-android-scrolling-bug
2. run `yarn start` & `yarn android`
3. Press inside the `WebView` and then start scrolling

**Expected behavior:**
`ScrollView` should be working properly after `WebView` is pressed

**Screenshots/Videos:**

https://user-images.githubusercontent.com/29244509/175817685-bee81377-1ddc-44c2-b906-5f54589264ba.mov

**Environment:**
 - OS: macOS Monterey
 - OS version: 12.4
 - react-native version: `0.68.2`
 - react-native-webview version: `11.22.3`

**Possible related issues:**
https://github.com/react-native-webview/react-native-webview/issues/2360, https://github.com/react-native-webview/react-native-webview/issues/2057

**Comment by keerthipativinaykumar** [comment]
one suggestion for the issue : use view tag for webview wrapping with scrollView will gets you bugs in lower versions of android and use flatlist for assigning webview in react native app instead of using scrollView and wrapping webview with view tag with collapsable={true} and webview with collapsable={false} and using domstorageenabled={true} and using container style with flex:0 flexGrow:1 and top:0, right:0, bottom:0, left:0 will result in improve permonece and solves issue not scrolling webveiw 

for using webview in flatlist assign webview url to dummy data in array for flatlist rendering and call the webview inside flatlist using array object model try it it will work as i assume

**Comment by mansilaad** [comment]
Still searching

**Comment by afras21** [comment]
For me if i scroll to the top, the webview is scrolling to the bottom. `NestedScrolling` is also enabled

**Comment by PhillipFraThailand** [comment]
Experiencing this issue with an animated title. I can't scroll the webview out of view as long as i am animating the height of my title component onScroll. Can we reopen this?

**Comment by swaroopaillinda** [comment]
@PhillipFraThailand hi did you find the solution I am also. facing same. issue
my webview inside scrollview is not scrolling

can you please tell if you have solved the issue

**Comment by PhillipFraThailand** [comment]
@swaroopaillinda i ended up disabling the scrolling animation on android for the specific cases where it happened
