### ISSUE TITLE
Audio not coming while live video streaming

### ISSUE THREAD

**Issue by clowndev21** [react-native-webview/react-native-webview#2571]
**Description:**
- I am using webview for a live video calling platform, where the video is working seamlessly, but audio is not coming. I tried the same in browser, both audio and video were coming. 
- Audio streaming is happening. I was able listen to audio in browser, when I tested with a android device and a web browser. 
- Its causing issue in Webview only.
- This was tested with all permission granted.

**Environment:**
 - OS: **Android** (Not tested with IOS)
 - OS version: 10
 - react-native version: 0.66.4
 - react-native-webview version: 11.18.1

**Comment by vinayn-mend** [comment]
@clowndev21 You mean the microphone issue ?

**Comment by mtperessoni** [comment]
It's happening the same thing here. The app request to user microphone and audio permissions. On android, both works nice, but on iOS, only camera works. I tried alot of configs, but i think this is a library problem

**Comment by mtperessoni** [comment]
Man, just a point to help u. I was with a problem like i said before. I got permission from camera and microphone. On android, it works perfect, showing the camera image and getting the audio. But on iOS the audio was not sending in Webview(i was using meet.jitsi to do a call with camera and microphone).

Looking to the jitsi configurations i saw that microphone was detected. When i spoke, the audio was detected by cellphone but not sended through the site running on WebView.

After alot of testes, i discovered that the problem was generated in iOS by UserAgent. The UserAgent that i was injecting in webview was "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36". 

I tried to use the user agent that i saw in another issue( https://github.com/react-native-webview/react-native-webview/issues/2356) when i was looking up for a solution and boooommm it worked. This UserAgent worked perfectly on iOS and Android too. Try to use this user agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko)".

Remember to guarantee that your microphone and camera permissions are working too.

**Comment by clowndev21** [comment]
still searching for solutions

**Comment by Desintegrator** [comment]
still searching for solutions

**Comment by kumarutsavrobosoft** [comment]
still searching for solution

**Comment by kumarutsavrobosoft** [comment]
setting this prop mediaPlaybackRequiresUserAction to true helped and it works smoothly now for me.

**Comment by kumarutsavrobosoft** [comment]
mediaPlaybackRequiresUserAction={false} will work

**Comment by Desintegrator** [comment]
@kumarutsavrobosoft tried mediaPlaybackRequiresUserAction={false} but no luck. Can you please provide some more details? Android sdk versions. All mobile <webview .../> props and web <video ... /> props. Or maybe example project

**Comment by Desintegrator** [comment]
and ReactNative and Webview lib versions
