### ISSUE TITLE
Webview android not saving cookies

### ISSUE THREAD

**Issue by h3thal** [react-native-webview/react-native-webview#2643]
y to log in from the webview on Android, after the next entry in the application, you must log in again. IOS doesn't have this problem.

Create a webview component specify a link to any site with authorization, for example github. specify parameters for the operation of cookies (sharedCookiesEnabled={true},thirdPartyCookiesEnabled={true}).
Then go to the application and complete the authorization. After authorization, restart the application and check authorization

It will be possible to continue working under an authorized user as on iOS

[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/ASm5CyG)

**Environment:**
 - OS: Android
 - OS version: 11
 - react-native version: 0.68.2
 - react-native-webview version: 11.18.1

**Comment by allan-simon** [comment]
does it work when you switch to an other "real page" (i.e not just navigating inside a single page app)

we've seen on our side that on our multipage app we were able to reproduce this when we stayed on the same page

**Comment by KoalaSat** [comment]
Hello, I have the same issue, after running inside webview:
```
document.cookie = `${key}=${value}`;
```
Checking `document.cookie` again returns `""`

**Comment by KoalaSat** [comment]
Testing it with `https://developer.mozilla.org/en-US/docs/web/api/document/cookie` actually works, so looks like it's related with using an internal URI

**Comment by allan-simon** [comment]
up

**Comment by KoalaSat** [comment]
For those with extra time or hurries, I solved it by using JS injection and EncryptedStorage.

Short description of the proposal https://github.com/Reckless-Satoshi/robosats/issues/258

And some key points on our implementation
1. Send cookie data to native: https://github.com/Reckless-Satoshi/robosats/blob/main/frontend/src/services/System/SystemNativeClient/index.ts#L32
2. Receiving and storing the data: https://github.com/Reckless-Satoshi/robosats/blob/main/mobile/App.tsx#L107
3. Receiving the data back and storing it on memory to avoid data inconsistencies and async read: https://github.com/Reckless-Satoshi/robosats/blob/main/frontend/src/services/Native/index.ts#L42

Extra hint: recovering stores data on start: https://github.com/Reckless-Satoshi/robosats/blob/main/mobile/App.tsx#L34

**Comment by allan-simon** [comment]
up

**Comment by allan-simon** [comment]
up

**Comment by rohanbasukala8848** [comment]
UP!!!!!

**Comment by robert-sfn** [comment]
In my case, the issue was resolved with the following code modification.

https://github.com/react-native-webview/react-native-webview/pull/2975/files

**Comment by kj-ahn-n** [comment]
In my case, the issue was resolved with the following code modification.

https://github.com/react-native-webview/react-native-webview/pull/2975/files

**Comment by IsaacConDosA** [comment]
any solution?

**Comment by rohanbasukala8848** [comment]
searching for solutions!
UP

**Comment by aminta** [comment]
up!!!

**Comment by manueltg89** [comment]
up!

**Comment by laogui** [comment]
up!  v13.6.3 still not work on android.

**Comment by Mokdasoo** [comment]
I am sharing the temporary solution that solved my problem.

Environment Overview: My app provides the entire service by displaying a single URL through a React Native WebView.

Encountered Problem:

1. Implemented login logic with cookies - Login (save cookies), logout (remove cookies), automatic login (check for cookies on app launch).
2. Works well on web and iOS.
3. Closing the app immediately after logging in or logging out on Android and then reopening it causes cookies to remain or not be saved. This results in being logged in even after logging out or being unable to automatically log in after logging in.
4. If you leave the app open for 5 minutes after logging in or out, close it, and then run it again, the cookies are reflected correctly.

Identified Cause: The issue is related to certain versions of Android WebView, where cookies are automatically synchronized every 5 minutes. If less than 5 minutes have passed, synchronization may not occur, causing the cookies not to be reflected.

Temporary Solution: Manually synchronize cookies in the Android WebView when cookie-related logic is executed on the web. A straightforward solution is to use the CookieManager.flush() method from the @react-native-cookies/cookies library. When executing cookie logic on the web, send a communication to the WebView, receive an event from WebView using onMessage, and execute CookieManager.flush() to manually synchronize.

Cookies are successfully applied after synchronization.

**Comment by DSp4wN** [comment]
UP

**Comment by Arian-Hamdi** [comment]
> I am sharing the temporary solution that solved my problem.
> 
> Environment Overview:
> 
> The environment of my app is an app that provides the entire service by displaying one URL through a single react native webview.
> 
> Encountered Problem:
> 
> 1. Implement login logic with cookies - Login (save cookies), logout (remove cookies), automatic login (determine the presence of cookies when running the app)
> 2. Works well on web and iOS.
> 3. If you close the app immediately after logging in or logging out on Android and then run the app again, cookies remain or are not saved, causing a problem where you remain logged in even after logging out or are unable to automatically log in even after logging in.
> 4. If you log in or log out and leave the app open for 5 minutes, close it and run it again, the cookies will be reflected well.
> 
> Identified Cause:
> 
> The reason is that in web views of certain versions of Android or higher, cookies are automatically synchronized every 5 minutes, but when less than 5 minutes have passed, the synchronization was not done and the cookies were not reflected.
> 
> Temporary Solution:
> 
> The solution was to manually synchronize cookies in the Android Webview when cookie-related logic was executed on my web. My easiest solution is to use the CookieManager.flush() method from the @react-native-cookies/cookies library. When cookie logic is executed on the web, you can set it to send communication to the Webview, receive an event from Webview onMessage, and execute CookieManager.flush(). You can then synchronize manually.
> 
> Cookies are applied well after synchronization.

Thanks man!

**Comment by ArianHamdi** [comment]
> I am sharing the temporary solution that solved my problem.
> 
> Environment Overview:
> 
> The environment of my app is an app that provides the entire service by displaying one URL through a single react native webview.
> 
> Encountered Problem:
> 
> 1. Implement login logic with cookies - Login (save cookies), logout (remove cookies), automatic login (determine the presence of cookies when running the app)
> 2. Works well on web and iOS.
> 3. If you close the app immediately after logging in or logging out on Android and then run the app again, cookies remain or are not saved, causing a problem where you remain logged in even after logging out or are unable to automatically log in even after logging in.
> 4. If you log in or log out and leave the app open for 5 minutes, close it and run it again, the cookies will be reflected well.
> 
> Identified Cause:
> 
> The reason is that in web views of certain versions of Android or higher, cookies are automatically synchronized every 5 minutes, but when less than 5 minutes have passed, the synchronization was not done and the cookies were not reflected.
> 
> Temporary Solution:
> 
> The solution was to manually synchronize cookies in the Android Webview when cookie-related logic was executed on my web. My easiest solution is to use the CookieManager.flush() method from the @react-native-cookies/cookies library. When cookie logic is executed on the web, you can set it to send communication to the Webview, receive an event from Webview onMessage, and execute CookieManager.flush(). You can then synchronize manually.
> 
> Cookies are applied well after synchronization.

Thanks man!

**Comment by kevgrig** [comment]
> In my case, the issue was resolved with the following code modification.
> 
> https://github.com/react-native-webview/react-native-webview/pull/2975/files

Thanks! Applying this patch fixed it for me. I think there was a regression in this library at some point in the last few years because I needed to update my app due to being "inactive" in Google Play, so I just upgraded Expo and all libraries without changing anything in my app and I encountered this issue whereas I didn't have it before. I applied the specified patch and now it's working as it did before.

**Comment by John251314** [comment]
e, anroid disabled cookie when load web assets from local, beacuse It`s not the standard web security model.
If you have the same issue, you should try load web assets with WebViewAssetLoader!

The document is here:
 https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader

good luck for you!

**Comment by expressed-tablegateway** [comment]
https://stackdev.space/questions/minimize-data-consumption-on-webview-for-mobile-devices



I detected the answer
