### ISSUE TITLE
window.ReactNativeWebView.postMessage is not a function

### ISSUE THREAD

**Issue by jackkinsella** [react-native-webview/react-native-webview#2680]
**Bug description:**

I'm getting a strange (and relatively rare) exception reported in Sentry.

```javascript
window.ReactNativeWebView.postMessage is not a function
```

This exists within a piece of code that explicitly checks if `window.ReactNativeWebView` is present

```javascript
if (window.ReactNativeWebView) {
  window.ReactNativeWebView.postMessage(message)
}
```

**To Reproduce:**

Because it happens rarely, I can't give exact reproduction steps. 

However:
- two instances were on a Pixel 4 (technically one of these was a Pixel 4a)
- one instance was on an SM-G996U

This appears to be sporadic, even for any given user. I.e. they will experience the bug briefly then it won't happen again.

**Environment:**
 - OS: Android
 - OS version: "Other" (that's all Sentry gave us)
 - react-native version: 0.68.2
 - react-native-webview version:  v11.22.1
 
 **Remarks**
 
 - Is it possible that `window.ReactNativeWebView` needs time to load its properties? 
- Is it possible that `window.ReactNativeWebView`  behaves differently depending on the OS/environment the code finds itself executed in? It seems like `postMessage` is a value instead of a function here.

**Comment by TheAlmightyBob** [comment]
> It seems like postMessage is a value instead of a function here

You would also get that error if `postMessage` doesn't exist on `ReactNativeWebView`. Unfortunately I have no idea how that would be possible... seems like maybe a quirk/bug of the Android WebView...

**Comment by mbLc** [comment]
I got almost the same bug, I don't know if I'm using the webview the wrong way but what I'm doing is: 
onLoadEnd calls a function and then webViewRef.current.injectJavaScript('injecting script here');

I'm getting: Cannot read properties of null (reading 'injectJavaScript'). Same for postMessage.

If I'm doing the same without this code and then adding it after the webview is loaded (hot reload) it's working fine.
The webview should be loaded since I'm calling it in onLoadEnd no?

I tried this on iOS.

**Comment by kassemitani** [comment]
We have the same the issue, reported by Bugsnag for Android devices.

**Comment by 17Amir17** [comment]
Same here

**Comment by 17Amir17** [comment]
Can we get this fixed? I'm still seeing this

**Comment by TheAlmightyBob** [comment]
@17Amir17 Based on the limited information thus far, this sounds like an issue with Android's WebView that this library can't do anything about. I could be wrong, but we don't have a repro and the info from @jackkinsella indicates that we are successfully invoking `addJavascriptInterface`.

I would be somewhat curious if `v11.21.2` behave[s|d] any differently, since there was some refactoring in `v11.22.0`... I would be surprised if that actually makes a difference though, as I don't think the refactoring would be related, but there were one or two things that unexpectedly broke there.

**Comment by 17Amir17** [comment]
This happened to me on `v11.18.1` and also after upgrading to `v11.26.0`

**Comment by antiline** [comment]
I have same issue on 11.25.1.

**Comment by mustvlad** [comment]
We have **Expo 47** and `"react-native-webview": "11.23.1"` in our project and we constantly receive errors on Sentry that no messages were received from the webview. Strange enough, I couldn't find this error in the web app but it seems like it's happening anyway.

From our estimation this happens to about 1% of users on Android. In our case the user can't even login in the app if the webview connection is not working well, so we constantly receive 1* reviews on the store.

Anyone here found a fix?

Seems like the issue happens across a wide range of devices and android versions so I couldn't tell if there's some special condition.

**Comment by adambeer** [comment]
Any updates on this? Im using version 11.626.0 and im using a ref for the viewer. `webviewRef.current.postMessage();` is not working on Android. I also tried with injectedJavascript with no luck:

`(function() {
    window.postMessage = function(data) {
        window.ReactNativeWebView.postMessage(data);
    };
})();`

**Comment by TheAlmightyBob** [comment]
@adambeer `webviewRef.current.postMessage()` different from the `window.ReactNativeWebView.postMessage` that this issue is about. Also, this issue is a very rare occurrence (which is why the problem/fix is unknown). If you're seeing a consistent failure, then that's something else.

**Comment by denissb** [comment]
I think 90% of the problem in this case is actually making a reproducible example which I tried to do today and failed. 
But this makes using the `window.ReactNativeWebView.postMessage` scary for mission critical functionality.

**Comment by 0xc22b** [comment]
Can it be about the WebView process being killed by the OS on Android, i.e., running out of memory or inactive for a period?

It seems that after onRenderProcessGone is called,  postMessage will be missing. And reload() doesn't help. Changing the WebView's key prop if onRenderProcessGone is called seems to fix the issue.

When the WebView process is killed and recreated, is something missing causing postMessage not a function?
