### ISSUE TITLE
findNodeHandle by webviewRef can not get native node id

### ISSUE THREAD

**Issue by cd-butterfly** [react-native-webview/react-native-webview#2722]
today i update from 10.7.0 to 11.23.1, on version 10.7.0 i used findNodeHandle(webviewRef.current) to get webview in native module。but now webview use useImperativeHandle，how can i get this now

**Comment by Gguigre** [comment]
Hi ! I'm facing the same issue.
It appeared in 11.22 I believe (https://github.com/react-native-webview/react-native-webview/compare/v11.21.2...v11.22.0)
Since it prepared the migration to Fabric.

However, the migration documentation recommands the creation of a forwardRef or a dedicated method to fetch the HostComponent that I can't see in 11.23.1 (latest version released when I'm writing this comment)
> https://reactnative.dev/docs/0.68/new-architecture-library-intro#preparing-your-javascript-codebase-for-the-new-react-native-renderer-fabric

Is it scheduled in the backlog ?

**Comment by TheAlmightyBob** [comment]
There was a PR to add something like the `getRef` @Gguigre suggests: https://github.com/react-native-webview/react-native-webview/pull/2691

It was closed because the events from React Native WebView still include the nativeTag, which was deemed sufficient for the submitter's use case. Would that be sufficient for yours?

**Comment by Gguigre** [comment]
Hi @TheAlmightyBob ! Thank's for your help on this :)
Although it's the information I'm looking for, I would expect an access to the nativeTag without having to wait for an event.

Actually, injecting the JS interface into the webview is something done on parent's component mount.
I guess you would suggest to do is on webview load right ?

**Comment by TheAlmightyBob** [comment]
@Gguigre I'm not really familiar with your use case, but yes I was thinking you could get the tag from the `onLoad` event.

**Comment by Gguigre** [comment]
For my usecase, I guess we can manage this way.
However, isn't there an issue with the typing of the events sent on onLoad/onLoadStart/onLoadEnd, ... ?
I actually see the target member (or the nativeTag) in the objects, but they don't appear in the typings of the nativeEvent.

I mean, it seems to functionnaly work but I guess it would be helping people with similar issues if the typing of `WebViewNavigationEvent` contained the typing of those.

Typicall, I see in the issue you mentioned that 

`WebViewNavigationEvent` (argument of the onLoad function as prop) should have a a structure as 
```
webViewNavigationEvent : {
  target : {
    _nativeTag : <number>
  },
  nativeEvent : {
   target : <number>
  }
}
```

However in the typing I see, we have

```
webViewNavigationEvent : {
  nativeEvent : {
    navigationType: 'click' | ...
    mainDocumentURL: string
  } <as WebViewNavigation>,
  target: <number as NodeHandle>
}```

**Comment by TheAlmightyBob** [comment]
@Gguigre Good catch. It looks like top-level `target` being a `number` instead of `NodeHandle` is an issue in the React Native types that was recently fixed: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62604

But even then, I'm guessing the corrected types might not expose the `nativeTag` property.

It might make sense to add `target` to the `WebViewNativeEvent` type... or perhaps have it extend React Native's `TargetedEvent` type...

**Comment by Gguigre** [comment]
Hi again ! 

Quick update on this issue, we had a look into the Anroid components tree to sort the differents tags that were returned by the Webview.

Turns out that, the `findNodeHandle` function, called on the webViewRef returns a `nativeTag` of the `ViewGroup` (containing the WebView) since it's the first "Native component" found by the tree search ; whereas the tag returned by the event is the actual webview tag :)

In this screenshot : the highlighted `ViewGroup` is the one which tag is returned by `findNodeHandle`. 
calling `nativeViewHierarchyManager.resolveView` with this tag confirms that we get a `ViewGroup` containing exactly 1 child, that is a `RNCWebView`

<img width="775" alt="image" src="https://user-images.githubusercontent.com/15343224/202455436-8ba5542e-747f-4110-9da7-e71ccd637370.png">
