### ISSUE TITLE
Can't scroll the content of WebView2

### ISSUE THREAD

**Issue by gangli66** [react-native-webview/react-native-webview#2747]
**Bug description:**

I use react-native-webview (WebView2) in my react-native-windows project. I can't scroll the content of WebView. It seems like it can't trigger onTouchStart/onTouchMove event because it can work well with mouse event.

**To Reproduce:**

1. Prepare a web project including scroll.
2. Prepare a RNW project and use react-native-webview(WebView2) which links to the web project.
3. Run the app and scroll the content of WebView with fingers.
**Expected behavior:**

The scroll can work well.
**Screenshots/Videos:**

**Environment:**
 - OS: Windows 10
 - OS version: 21H2
 - react-native version: 0.68.3
 - react-native-windows version: 0.68.15
 - react-native-webview version: 11.23.1

**Comment by chiaramooney** [comment]
To clarify, do you mean that you can scroll with your mouse, but with touch, scrolling does not work? If so this is expected behavior for out of the box RNW. Currently, a workaround is needed to enable touch scrolling for webviews. See here https://github.com/microsoft/react-native-windows/issues/6287. Closing issue for now. Reopen if issue persists.
