### ISSUE TITLE
injectedJavaScriptForMainFrameOnly not work .

### ISSUE THREAD

**Issue by jamninetyfive** [react-native-webview/react-native-webview#2768]
**Bug description:**

i wanna injectedJavaScript for the all iframe. but it's doen't work now. even i set injectedJavaScriptForMainFrameOnly = {false}

I think this may be the failure of this PR https://github.com/react-native-webview/react-native-webview/pull/1119 

**To Reproduce:**

**Expected behavior:**
i got 3 iframes in my page. when i console localtion.href i got about:blank
 LOG  onMessage Hello from inside:      about:blank
 LOG  onMessage Hello from inside:      https://www.xxx.com/detail/xxx.html
 LOG  onMessage Hello from inside:      about:blank

 LOG  onMessage Hello from inside:      about:blank
 LOG  onMessage Hello from inside:      https://www.xxx.com/detail/xxx.html

**Screenshots/Videos:**

**Environment:**
 - OS:iOS Android
 - OS version:16.1.1
 - react-native version: 0.70.6
 - react-native-webview version: 11.25.0

**Comment by jamninetyfive** [comment]
@shirakaba can you help me

**Comment by shirakaba** [comment]
@Stephen-Song I've not been involved in this library since 2020. Best to create a new issue with a minimum working example that reproduces the problem. This issue as it is lacks enough detail for anyone to tell whether the WebView component was set up correctly or not.

Please study the test cases in https://github.com/react-native-webview/react-native-webview/blob/master/example/examples/Injection.tsx and check where your usage may differ from the intended usage.
