### ISSUE TITLE
Android 12 - Webview inserts new lines when placing cursor

### ISSUE THREAD

**Issue by AndriyZahura** [react-native-webview/react-native-webview#2786]
**Bug description:**
I am using a library called react-native-rich-editor in order to edit html content in my react native app - https://github.com/wxik/react-native-rich-editor#readme. I have also tried react-native-cn-quill - https://github.com/imnapo/react-native-cn-quill, which is also built on top of react-native-webview, and gives the same result. I have an html that goes like this - 

```
'<p>If you have any questions, please contact me by xxxxxx1988v@gmail.com, or (xxx) xxx-xxxx</p>'
'<p>Office xxxx.xxxxxxxx@gmail.com or (xxx) xxx-xxxx</p>'
```

*there are actual numbers and email instead of 'x'

Using Samsung Galaxy S21 FE, every time I place a cursor anywhere, it inserts the `<p><br></p>` inside every `</p><p>`.
Which gives the next string - 

```
'<p>If you have any questions, please contact me by andrey1988v@gmail.com, or (xxx) xxx-xxxx</p>'
'<p><br></p>'
'<p>Office xxxx.xxxxxxxx@gmail.com or (xxx) xxx-xxxx</p>'
```

If there are more than 1 `</p><p>`, break will be placed inside each.

Please note, that I do not enter any additional text, paragraph adds after every cursor movement.

I am not sure if it helps, but here is my RichEditor code

```
{message || message === '' ? (
    <View key={'html'} style={style.paddingTop}>
        <RichEditor
            style={messageValid ? style.richEditor : style.richEditorInvalid}
            ref={richText}
            initialContentHTML={message}
            onChange={(data) => setMessage(data || '')}
        />
    </View>
) : null}
```

Please note that I was able to reproduce it only on Samsung Galaxy S21 FE (real device). I have also tried Xiaomi Redmi 7 and iPhone 8, but there it works fine. 

Also, I recently updated my Android targetSDK to 31.

Edit: The problem seems to appear only on Samsung devices which use One UI 5+

**To Reproduce:**
`npm i react-native-pell-rich-editor`

```
const richText = useRef();
const message = '<p>Dear client, xxxxxx1988v@gmail.com (xxx) xxx-xxxx</p>\n' +
'<p>This is Xxx Xxxxx, with Xxxx QA 1.</p>\n' +
'<p>We have an appointment scheduled, and I want to let you know that I am on my way.</p>\n' +
'<p>Estimated arrival time: 30min</p>\n' +
'<p>If you have any questions, please contact me by xxxxxx1988v@gmail.com, or (xxx) xxx-xxxx</p>\n' +
'<p>Office xxxx.xxxxxxxx@gmail.com or (xxx) xxx-xxxx</p>\n' +
'<p>Thank you!&nbsp;</p>'

<View key={'html'}>
        <RichEditor
            style={{height: 200, width: 200}}
            ref={richText}
            initialContentHTML={message}
            onChange={(data) => setMessage(data || '')}
        />
</View>
```

**Expected behavior:**
No additional paragraphs and html tags in general should be added on cursor movement.

**Screenshots/Videos:**
If it is required, I can try to provide a video. Please reply if it is necessary. 

**Environment:**
 - OS: Android
 - OS version: 12+
 - react-native version: 0.67.5
 - react-native-webview version: 11.26.0
  - react-native-pell-rich-editor: 1.8.8

**Comment by jordoh** [comment]
I'm seeing the same issue with a rich text editor (ProseMirror) inside react-native-webview. This only occurs on devices that are updated to Samsung One UI 5 (Android 13), which has been rolling out since last November, but is now getting to more common devices (so we are seeing it more in the wild).

The problem appears to be the "Suggest text corrections" feature that is powered by Grammarly. As an end-user, you can fix the issue by disabling the "Suggest text corrections" option entirely, or just for the specific app, as pictured here:
![image](https://user-images.githubusercontent.com/450345/217609603-a7a96f3b-817a-4344-b569-ff341db346c4.png)

The issue can also be fixed by using GBoard instead of the Samsung keyboard.

----

The exact issue appears to be that - in some cases, depending on the content - the keyboard will select the entire contentEditable document and replace it with the following changes: 
1. Anything that is not a plain `<p>text</p>` will be unwrapped to a plain `<p>text</p>`
2. Any empty paragraphs - or paragraphs containing a single `<br />` will be doubled
This happens when the selection is changed by the user.

----
While this doesn't immediately seem related to react-native-webview, it should be noted that this does not reproduce using the same contentEditable-based editor in Chrome or Samsung Internet. It only reproduces in react-native-webview (which used the Android system webview that is lists itself as `Chrome 109.0.5414.117`). As an issue with the Android system webview and Samsung keyboard, it seems unlikely to be something that react-native-webview can (or should) do anything about.

**Comment by Phong-TH** [comment]
@AndriyZahura did you resolve this issue without disabling Grammarly? I have the same issue with the html editor. If I change the input mode to url, Grammarly is disabled but the auto-correct and spell check does not work.

**Comment by AndriyZahura** [comment]
@Phong-TH sorry for the late reply. I did with this workaround, not sure if there is an actual solution

```
import {RichEditor} from 'react-native-pell-rich-editor';

export const IS_SAMSUNG =
  Platform.OS === 'android' && getBrand()?.toLowerCase() === 'samsung' && parseFloat(getSystemVersion()) >=12;
  
<RichEditor
  initialContentHTML={
    IS_SAMSUNG
    ? message
    .replaceAll('<p>', '<div style="margin-bottom: 10px">')
    .replaceAll('</p>', '</div>')
    : message
  }
/>
```
