### ISSUE TITLE
OAuth login authorization flows support required

### ISSUE THREAD

**Issue by idan666** [react-native-webview/react-native-webview#2876]
Hi,
Part of an integration with a 3rd party payment platform,
web implementation with a vendor required authorizing service with oauth 2.0 login flow.

When running this in the webview, i get an error browser isn't supported.
is there any intention updating security measures to support such requirements?

the suggested solution by the payment platform is directing app users to an external browser, which i wish to avoid.

**Comment by TheAlmightyBob** [comment]
@idan666 My understanding is that OAuth does not support/recommend using WebViews in general due to security concerns, not specific to this particular package. So I don't think there's any feature that could be added here.

You might have luck with https://github.com/proyecto26/react-native-inappbrowser (but I haven't used it for this).
