### ISSUE TITLE
injectJavascript and postMessage is not working after upgrading lib to 11.22.0

### ISSUE THREAD

**Issue by mohitarora777** [react-native-webview/react-native-webview#2893]
Hi, i was using postMessage on webview ref in a RN project with webview version 11.15.0, recently i tried switching to version 11.22.6 to solve the issue with sdk 33, after that postMessage stopped working. On web `message` event is not firing. I checked on all the versions between 11.15.0 & 11.22.6. The issue starts appearing from 11.22.0. I tried using injectJavascript but that is also not working. 

Sample: The sample mentioned in the docs is also not working:

import React, { Component } from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';

export default class App extends Component {
  render() {
    const run = `
      document.body.style.backgroundColor = 'blue';
      true;
    `;

    setTimeout(() => {
      this.webref.injectJavaScript(run);
    }, 3000);

    return (
      <View style={{ flex: 1 }}>
        <WebView
          ref={(r) => (this.webref = r)}
          source={{
            uri: 'https://github.com/react-native-webview/react-native-webview',
          }}
        />
      </View>
    );
  }
}

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 0.66.3
 - react-native-webview version: 11.22.0

**Comment by TheAlmightyBob** [comment]
Have you tried newer Android versions? There was a related report that was specific to older Android versions: https://github.com/react-native-webview/react-native-webview/issues/2812 (but that was still using an older version of `react-native-webview`, so unrelated to `11.22.0`)

You also remind me of https://github.com/react-native-webview/react-native-webview/issues/2810, but that seemed fairly specific to `goBack`.

Your code ran fine (after fixing typos) in Expo Snack: https://snack.expo.dev/oT8JBR3fS

**Comment by mohitarora777** [comment]
@TheAlmightyBob i tried in android version 9 and 13. Did not work in both of them, Also i tried one another method "refresh" that would only cause a loader with white screen to come up on screen and it never go away. The problem seems with Commands.postMessage , Commands.refresh etc, those are not working. I checked the PR, in 11.22.0 we have replaced UIManager.dispatchCommand with codegenNativeCommands. Strangely these are working fine on IOS.

**Comment by TheAlmightyBob** [comment]
If you could share a full project that reproduces the issue that might help, but since the code you shared worked fine in Expo Snack (and I've not been able to reproduce any such issue locally), I can't help thinking there must be some kind of environment factor.... you might need to debug this yourself. Have you tried attaching Android Studio and putting a breakpoint/log [here](https://github.com/react-native-webview/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L733) to see if it's trying to invoke the functions?

(I sometimes have issues with breakpoints in Android Studio, which is why I mention log statements as an alternative...)
