### ISSUE TITLE
[Windows] show blank page in release mode

### ISSUE THREAD

**Issue by icefee** [react-native-webview/react-native-webview#3112]
It's works on dubug mode, but show nothing on release.

```jsx
<WebView
     ref={
        (r) => {
           webRef.current = r;
        }
      }
      source={require('../assets/html/chart/line-chart.html')}
      onLoad={onLoad}
      useWebView2
 />
````

**Environment:**
 - OS: Windows 10
 - OS version: 19045.3324
 - react-native version: 0.72.4
 - react-native-webview version: 13.3.1
 - Visual Studio version: Microsoft Visual Studio Community 2022   17.6.5

**Comment by chiaramooney** [comment]
Do you have a simple repro of this? (i.e. is the case you're showing here an app that only has the webview community module added and just this one webview is rendered)

Blank screen bugs in Release mode can be common and are often caused by a variety of errors. We have a working example of a webivew in release mode here (https://github.com/microsoft/react-native-gallery), so we know we have a base case of webview working in release. It may be that another community module is causing errors, so it would be good to get a simple repro first.

**Comment by icefee** [comment]
@chiaramooney 
Yes, in the gallery, all of the samples load url from remote, and my case is loading local html file from assets folder, I created a minimal project.
[https://github.com/icefee/react_native_windows_webview_sample](https://github.com/icefee/react_native_windows_webview_sample)
Run it in visual studio code in release mode

**Comment by icefee** [comment]
Ok, thanks a lot. ❤️
