### ISSUE TITLE
IOS: Infinite loading when showing webview

### ISSUE THREAD

**Issue by NuneGharibyan** [react-native-webview/react-native-webview#3249]
**Bug description:**
On my ios device, I'm getting an infinite loading and the web page is not being opened (it is not always reproducible). The same code works fine on Android. And there is no error message being displayed
```
  <WebView
        style={loginWindowStyles.webView}
        scalesPageToFit={true}
        source={{uri}}
        renderLoading={renderLoading}
        onMessage={onMessage}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        startInLoadingState={true}
        onError={() => console.log('error')}
        useWebKit={true}
        limitsNavigationsToAppBoundDomains={true}
      />
```

**Environment:**
 - OS: iOS
 - OS version: iOS 16.6.1
 - react-native version: 0.72.6
 - react-native-webview version: 13.2.2

**Comment by juan-martin-ts** [comment]
Did you solve this? thx

**Comment by NuneGharibyan** [comment]
no

**Comment by jerom98** [comment]
startInLoadingState={false} worked for me

**Comment by daviCamarinha** [comment]
Any news from this issue? I have the same error here. Works fine in Android, but ios just a blank screen

**Comment by amrdraz** [comment]
A similar issue started happening with me, trying to figure out why
I'm using expo sdk 50 where I prebuild

android works fine

IOs loads indefinitely but doesn't if I use expo Update and push a new bundle, this makes me suspect I need to refresh the page somehow, this is  difficult to debug because it only happens if I'm using expo dev-client as that does what ever expo update also does. so far I'm only able to reproduce it on production or internal builds and reading logs from logging tool 😄

**Comment by Bardiamist** [comment]
Same

**Comment by ArneWittouck** [comment]
Has anyone found a solution to this problem? I'm running into the same problem now...

**Comment by namdh03** [comment]
Same
