### ISSUE TITLE
[iOS] Completion handler passed to -[RNCWebViewImpl webView:runJavaScriptAlertPanelWithMessage:initiatedByFrame:completionHandler:] was not called

### ISSUE THREAD

**Issue by LaGregance** [react-native-webview/react-native-webview#3503]
**Bug description:**
I got the following crash in my Firebase Crashlytics console:
```
Fatal Exception: NSInternalInconsistencyException
Completion handler passed to -[RNCWebViewImpl webView:runJavaScriptAlertPanelWithMessage:initiatedByFrame:completionHandler:] was not called

0  CoreFoundation                 0x83f20 __exceptionPreprocess
1  libobjc.A.dylib                0x16018 objc_exception_throw
2  CoreFoundation                 0x1826dc -[NSException initWithCoder:]
3  WebKit                         0x166288 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
4  WebKit                         0x1661e0 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
5  WebKit                         0x74d5a4 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
6  libsystem_blocks.dylib         0x21b0 _call_dispose_helpers_excp
7  libsystem_blocks.dylib         0x2164 _Block_release
8  WebKit                         0x73ddb8 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
9  WebKit                         0x897cc8 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
10 WebKit                         0x897988 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
11 WebKit                         0x198770 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
12 WebKit                         0x7a3fb0 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
13 WebKit                         0x8716b0 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
14 WebKit                         0x871964 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
15 WebKit                         0xcd44e0 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
16 WebKit                         0x1efe64 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
17 WebKit                         0x1efc68 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
18 WebKit                         0x1ef76c (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
19 WebKit                         0x245ac (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
20 WebKit                         0x1072e0 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
21 WebKit                         0x98834 (Missing UUID 2070c7a26aaf39f1b5c7abc26fbcaeb7)
22 JavaScriptCore                 0x5a9e8 WTF::RunLoop::performWork()
23 JavaScriptCore                 0x5b910 WTF::RunLoop::performWork(void*)
24 CoreFoundation                 0x56834 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
25 CoreFoundation                 0x567c8 __CFRunLoopDoSource0
26 CoreFoundation                 0x54298 __CFRunLoopDoSources0
27 CoreFoundation                 0x53484 __CFRunLoopRun
28 CoreFoundation                 0x52cd8 CFRunLoopRunSpecific
29 GraphicsServices               0x11a8 GSEventRunModal
30 UIKitCore                      0x40a90c -[UIApplication _run]
31 UIKitCore                      0x4be9d0 UIApplicationMain
32 MyApp                     0x42e4 main + 8 (main.m:8)
33 ???                            0x1c111de4c (Missing)
```

**To Reproduce:**
Unfortunately I can't reproduce by myself, so I don't know when it's happen.  
There is some similar issue (#1585 & #1325), but they are old and apparently assumed as resolved. 

**Expected behavior:**
No crash

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 17.4.1 / 17.5.1
 - react-native version: 0.74.3
 - react-native-webview version: 13.10.5

Thanks for your help.

**Comment by LaGregance** [comment]
More precision: this issue appear after I upgraded the package from version 11.26.0 to 13.10.5.
It's appear the version 11.26.0 doesn't include the fabric integration, and even if I now use the 13.10.5 version, I still not use the new architecture, maybe this is linked...

**Comment by Bardiamist** [comment]
Happened on prod once on react-native-webview@13.10.4

**Comment by mrand15** [comment]
We are now seeing this crash, although we haven't updated the react-native-webview version recently. Suspect it may be related to the upgrade to RN v0.74 ?

**Comment by LaGregance** [comment]
Indeed I just upgrade RN too at the same time of this package, it can be linked.

**Comment by zbranevichfinstek** [comment]
Faced the same issues on prod. We are using "react-native-webview": "13.4.0".
More detailed backtrace, but still unclear how to reproduce.

<details><summary>Backtrace </summary>
<p>

Exception Type:  SIGABRT

Exception Codes: #0 at 0x1d671342c
Crashed Thread:  0

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[RNCWebViewImpl webView:runJavaScriptConfirmPanelWithMessage:initiatedByFrame:completionHandler:] was not called'

Last Exception Backtrace:
0   CoreFoundation                       0x000000018d658f20 __exceptionPreprocess + 164
1   libobjc.A.dylib                      0x00000001854ea018 objc_exception_throw + 56
2   CoreFoundation                       0x000000018d7576dc +[NSException raise:format:] + 108
3   WebKit                               0x00000001a2966288 WebKit::CompletionHandlerCallChecker::~CompletionHandlerCallChecker() + 140
4   WebKit                               0x00000001a29661e0 WTF::ThreadSafeRefCounted<WebKit::CompletionHandlerCallChecker, (WTF::DestructionThread)0>::deref() const + 40
5   WebKit                               0x00000001a2f4d67c WTF::BlockPtr<void (bool)> WTF::BlockPtr<void (bool)>::fromCallable<WebKit::UIDelegate::UIClient::runJavaScriptConfirm(WebKit::WebPageProxy&, WTF::String const&, WebKit::WebFrameProxy*, WebKit::FrameInfoData&&, WTF::Function<void (bool)>&&)::$_9>(WebKit::UIDelegate::UIClient::runJavaScriptConfirm(WebKit::WebPageProxy&, WTF::String const&, WebKit::WebFrameProxy*, WebKit::FrameInfoData&&, WTF::Function<void (bool)>&&)::$_9)::'lambda'(void const*)::__invoke(void const*) + 32
6   libsystem_blocks.dylib               0x00000001ea4a81b0 _call_dispose_helpers_excp + 44
7   libsystem_blocks.dylib               0x00000001ea4a8164 _Block_release + 248
8   libsystem_blocks.dylib               0x00000001ea4a81b0 _call_dispose_helpers_excp + 44
9   libsystem_blocks.dylib               0x00000001ea4a8164 _Block_release + 248
10  UIKitCore                            0x000000018fef76a8 -[UIAlertController _clearActionHandlers] + 152
11  UIKitCore                            0x000000018fef59a4 -[UIAlertController dealloc] + 300
12  UIKitCore                            0x000000018fdcf000 -[UIPresentationController .cxx_destruct] + 300
13  libobjc.A.dylib                      0x00000001854d8c3c object_cxxDestructFromClass(objc_object*, objc_class*) + 112
14  libobjc.A.dylib                      0x00000001854d8300 objc_destructInstance + 76
15  libobjc.A.dylib                      0x00000001854d82a8 _objc_rootDealloc + 76
16  UIKitCore                            0x000000018fc34ce0 -[UIPresentationController dealloc] + 348
17  libsystem_blocks.dylib               0x00000001ea4a8b74 bool HelperBase<GenericInline>::disposeCapture<(HelperBase<GenericInline>::BlockCaptureKind)3>(unsigned int, unsigned char*) + 64
18  libsystem_blocks.dylib               0x00000001ea4a86dc HelperBase<GenericInline>::destroyBlock(Block_layout*, bool, unsigned char*) + 156
19  libsystem_blocks.dylib               0x00000001ea4a81c8 _call_dispose_helpers_excp + 68
20  libsystem_blocks.dylib               0x00000001ea4a8164 _Block_release + 248
21  UIKitCore                            0x000000018fb89ed8 -[_UIViewControllerTransitionContext .cxx_destruct] + 76
22  libobjc.A.dylib                      0x00000001854d8c3c object_cxxDestructFromClass(objc_object*, objc_class*) + 112
23  libobjc.A.dylib                      0x00000001854d8300 objc_destructInstance + 76
24  libobjc.A.dylib                      0x00000001854d82a8 _objc_rootDealloc + 76
25  UIKitCore                            0x000000018fb67828 -[_UIViewControllerTransitionContext dealloc] + 52
26  UIKitCore                            0x000000018fb67640 -[_UIViewControllerOneToOneTransitionContext dealloc] + 68
27  libsystem_blocks.dylib               0x00000001ea4a8b74 bool HelperBase<GenericInline>::disposeCapture<(HelperBase<GenericInline>::BlockCaptureKind)3>(unsigned int, unsigned char*) + 64
28  libsystem_blocks.dylib               0x00000001ea4a86dc HelperBase<GenericInline>::destroyBlock(Block_layout*, bool, unsigned char*) + 156
29  libsystem_blocks.dylib               0x00000001ea4a81c8 _call_dispose_helpers_excp + 68
30  libsystem_blocks.dylib               0x00000001ea4a8164 _Block_release + 248
31  UIKitCore                            0x000000018f8b9b28 -[UIViewAnimationBlockDelegate .cxx_destruct] + 48
32  libobjc.A.dylib                      0x00000001854d8c3c object_cxxDestructFromClass(objc_object*, objc_class*) + 112
33  libobjc.A.dylib                      0x00000001854d8300 objc_destructInstance + 76
34  libobjc.A.dylib                      0x00000001854d82a8 _objc_rootDealloc + 76
35  libsystem_blocks.dylib               0x00000001ea4a8b74 bool HelperBase<GenericInline>::disposeCapture<(HelperBase<GenericInline>::BlockCaptureKind)3>(unsigned int, unsigned char*) + 64
36  libsystem_blocks.dylib               0x00000001ea4a86dc HelperBase<GenericInline>::destroyBlock(Block_layout*, bool, unsigned char*) + 156
37  libsystem_blocks.dylib               0x00000001ea4a81c8 _call_dispose_helpers_excp + 68
38  libsystem_blocks.dylib               0x00000001ea4a8164 _Block_release + 248
39  libdispatch.dylib                    0x00000001954fddd4 _dispatch_client_callout + 16
40  libdispatch.dylib                    0x000000019550c5a4 _dispatch_main_queue_drain + 984
41  libdispatch.dylib                    0x000000019550c1b8 _dispatch_main_queue_callback_4CF + 40
42  CoreFoundation                       0x000000018d62b710 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
43  CoreFoundation                       0x000000018d628914 __CFRunLoopRun + 1992
44  CoreFoundation                       0x000000018d627cd8 CFRunLoopRunSpecific + 604
45  GraphicsServices                     0x00000001d24d81a8 GSEventRunModal + 160
46  UIKitCore                            0x000000018fc6090c -[UIApplication _run] + 884
47  UIKitCore                            0x000000018fd149d0 UIApplicationMain + 336
48  GMI Edge                             0x00000001042e04c8 main (main.m:8)
49  ???                                  0x00000001b0cd9e4c 0x00000001b0cd9e4c

Thread 0 Crashed:
0   libsystem_kernel.dylib               0x00000001d671342c __pthread_kill + 8
1   libsystem_c.dylib                    0x00000001955b6ba0 abort + 176
2   GMI Edge                             0x0000000104674790 uncaught_exception_handler.cold.1 + 24
3   GMI Edge                             0x0000000104658584 uncaught_exception_handler (PLCrashReporter.m:371)
4   CoreFoundation                       0x000000018d757984 __handleUncaughtException + 656
5   libobjc.A.dylib                      0x0000000185505e20 _objc_terminate() + 128
6   GMI Edge                             0x000000010464ca84 MSACCrashesUncaughtCXXTerminateHandler() (MSACCrashesCXXExceptionHandler.mm:161)
7   libc++abi.dylib                      0x00000001ea3d0068 std::__terminate(void (*)()) + 12
8   libc++abi.dylib                      0x00000001ea3d000c std::terminate() + 104
9   libdispatch.dylib                    0x00000001954fdde8 _dispatch_client_callout + 36
10  libdispatch.dylib                    0x000000019550c5a4 _dispatch_main_queue_drain + 984
11  libdispatch.dylib                    0x000000019550c1b8 _dispatch_main_queue_callback_4CF + 40
12  CoreFoundation                       0x000000018d62b710 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
13  CoreFoundation                       0x000000018d628914 __CFRunLoopRun + 1992
14  CoreFoundation                       0x000000018d627cd8 CFRunLoopRunSpecific + 604
15  GraphicsServices                     0x00000001d24d81a8 GSEventRunModal + 160
16  UIKitCore                            0x000000018fc6090c -[UIApplication _run] + 884
17  UIKitCore                            0x000000018fd149d0 UIApplicationMain + 336
18  GMI Edge                             0x00000001042e04c8 main (main.m:8)
19  ???                                  0x00000001b0cd9e4c 0x0 + 0

</p>
</details>

**Comment by franmiorin** [comment]
I found the reason for this crash. In my case, the webpage loaded in the WebView contains a form with mandatory fields. If I try to navigate to another screen without completing these fields, the form triggers a JavaScript alert, which causes the crash on iOS. To resolve this, I injected some JavaScript code to override the form's alert function, replacing it with a React Native alert. This allows the app to recognize the alert and handle it properly.

 ```
const handleMessage = (event: { nativeEvent: { data: string } }) => {
    try {
      const data = JSON.parse(event.nativeEvent.data);
      if (data.type === "ALERT") {
        // Display the alert message using React Native's Alert
        Alert.alert(
          "",
          data.message,
          [{ text: "OK", onPress: () => console.log("OK Pressed") }],
          { cancelable: true },
        );
      }
    } catch (e) {
      console.error("Failed to parse message from WebView:", e);
    }
  };

  const injectedJavaScript = '
  (function() {
    // Preserve the original alert function if needed
    window.originalAlert = window.alert;
    
    // Override the alert function
    window.alert = function(message) {
      // Send a message to React Native
      window.ReactNativeWebView.postMessage(JSON.stringify({ type: 'ALERT', message: message }));
    };
  })();
';
```

And add them to your WebView

```
injectedJavaScript={injectedJavaScript}
onMessage={handleMessage}
javaScriptEnabled
domStorageEnabled
```

**Comment by rodmastro32** [comment]
did you find a solution here? im getting this too after upgrading to react native 0.78 and webview package at 13.16.0
