### ISSUE TITLE
`onNavigationStateChange` is not called when navigating when `enableApplePay` is set to true

### ISSUE THREAD

**Issue by mvaivre** [react-native-webview/react-native-webview#3544]
**Bug description:**
Navigation behaviour seems different whether `enableApplePay` is set or not. Then it's set to `true`:
- `onNavigationStateChange` isn't called when the url's domain changes
- The page reloads fully when the URL state changes (white flash between screens). Navigation is much smoother (no full reload) when `enableApplePay` is set to false.

**To Reproduce:**
Add the `enableApplePay`. Try to log updates on `onNavigationStateChange`. 

**Expected behavior:**
`onNavigationStateChange` is supposed to be executed when navigating.

**Environment:**
 - OS: iOS
 - OS version: iOS 18 beta
 - react-native version: 0.74.2
 - react-native-webview version:

**Comment by james-ovens-eurostar** [comment]
Hi 👋  I think this one is still an issue in the latest version, and I also have a workaround for this.

In these lines of code here:
https://github.com/react-native-webview/react-native-webview/blob/master/apple/RNCWebViewImpl.m#L1834C3-L1863

we have:

```
  if(self.enableApplePay){
    if (self.postMessageScript){
      [wkWebViewConfig.userContentController addScriptMessageHandler:[[RNCWeakScriptMessageDelegate alloc] initWithDelegate:self]
                                                                name:MessageHandlerName];
    }
    return;
  }

  NSString *html5HistoryAPIShimSource = [NSString stringWithFormat:
                                           @"(function(history) {\n"
                                         "  function notify(type) {\n"
                                         "    setTimeout(function() {\n"
                                         "      window.webkit.messageHandlers.%@.postMessage(type)\n"
                                         "    }, 0)\n"
                                         "  }\n"
                                         "  function shim(f) {\n"
                                         "    return function pushState() {\n"
                                         "      notify('other')\n"
                                         "      return f.apply(history, arguments)\n"
                                         "    }\n"
                                         "  }\n"
                                         "  history.pushState = shim(history.pushState)\n"
                                         "  history.replaceState = shim(history.replaceState)\n"
                                         "  window.addEventListener('popstate', function() {\n"
                                         "    notify('backforward')\n"
                                         "  })\n"
                                         "})(window.history)\n", HistoryShimName
  ];
  WKUserScript *userScript = [[WKUserScript alloc] initWithSource:html5HistoryAPIShimSource injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:YES];
  [wkWebViewConfig.userContentController addUserScript:userScript];
```

This means if enableApplePay is enabled then this block will return before html5HistoryAPIShimSource gets created and registered.

I have for now added a patch that moves this return to just after the shim is created and this appears to be working now and doesn't have any effect on Apple Pay.

I imagine a proper solution for this might involve looking at what else might be missing because of this early return but this fixed my needs to be able to have a browser back button to control the webview in my case.

I think this issue should at least be reopened as its definitely still a problem in the latest version.
